#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
TOTAL_STAGES=9
TOTAL_MINUTES=40

# Values are remembered here between runs (Enter keeps a saved value), then
# pushed to the VPS at stage 6. Matches the ~/.config/fein/ convention.
mkdir -p "$HOME/.config/fein"
ENV_FILE="$HOME/.config/fein/funnel.env"

VPS="root@167.88.38.87"
vps() { ssh -o BatchMode=yes "$VPS" "$@"; }

banner "fein booking funnel setup"

# ── 1 · Namecheap DNS ─────────────────────────────────────────────────────
stage "Namecheap DNS for fein.vc" 8
say "One visit fixes everything DNS: the parked site, the api subdomain,"
say "and (next stage) Resend's sending records."
open_url "https://ap.www.namecheap.com/domains/list/"
step "Open fein.vc → Manage → Advanced DNS."
step "DELETE the 'URL Redirect Record' on @ and the CNAME on www that points"
say "  at parkingpage.namecheap.com."
step "ADD these records:"
say "    A      @      185.199.108.153"
say "    A      @      185.199.109.153"
say "    A      @      185.199.110.153"
say "    A      @      185.199.111.153"
say "    CNAME  www    clippycommits.github.io."
say "    A      api    167.88.38.87"
warn "Leave the MX (smtp.google.com) and the google-site-verification TXT alone."
pause "Done in Namecheap? Press Enter."

# ── 2 · Resend domain ─────────────────────────────────────────────────────
stage "Resend — add the sending domain" 7
say "Emails go out as daniel@fein.vc, so Resend must verify the domain."
open_url "https://resend.com/domains"
step "Log in (same account as Cereal Milk is fine) → Add Domain → fein.vc."
step "Pick the region closest to you (eu-west works), then Resend shows"
say "  three DNS records (an MX and a TXT on 'send', and a resend._domainkey TXT)."
step "Copy each one into Namecheap Advanced DNS EXACTLY as shown — host and"
say "  value both. They live on subdomains, so Google mail is untouched."
step "Back in Resend, press 'Verify DNS Records'. Propagation can take a few"
say "  minutes; 'Pending' is fine, re-check after the wizard."
pause "Records added and verification started? Press Enter."

# ── 3 · Resend API key ────────────────────────────────────────────────────
stage "Resend — API key" 2
open_url "https://resend.com/api-keys"
step "Create API Key → name it 'fein-leads', permission 'Sending access',"
say "  domain fein.vc → Create. Copy the key (shown once, starts re_)."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
write_env RESEND_API_KEY "$RESEND_API_KEY"

# ── 4 · cal.com event type ────────────────────────────────────────────────
stage "cal.com — your booking page" 8
say "This is the link every email and the site's success screen point at."
open_url "https://app.cal.com/signup"
step "Sign up (or log in) — the free plan does everything we need."
step "Set your availability (Availability → working hours)."
step "Event Types → New: title 'fein intro', 30 minutes, add Google Meet or"
say "  whatever you prefer as the location."
step "Copy the event's public link (looks like https://cal.com/<you>/fein-intro)."
ask CAL_LINK "Paste the booking link:"
write_env CAL_LINK "$CAL_LINK"

# ── 5 · cal.com webhook ───────────────────────────────────────────────────
stage "cal.com — booking webhook" 4
CALCOM_WEBHOOK_SECRET=$(_existing CALCOM_WEBHOOK_SECRET || true)
if [[ -z "$CALCOM_WEBHOOK_SECRET" ]]; then
  CALCOM_WEBHOOK_SECRET=$(openssl rand -hex 24)
  write_env CALCOM_WEBHOOK_SECRET "$CALCOM_WEBHOOK_SECRET"
fi
say "When someone books, cal.com tells the lead service so the 3-day nudge"
say "email is cancelled. The signing secret below was generated for you."
open_url "https://app.cal.com/settings/developer/webhooks/new"
step "Subscriber URL:  https://api.fein.vc/webhooks/calcom"
step "Event triggers:  tick 'Booking created' only."
step "Secret — paste exactly this:"
printf '\n      %s%s%s\n\n' "$BOLD" "$CALCOM_WEBHOOK_SECRET" "$RESET"
step "Save the webhook."
pause "Webhook saved? Press Enter."

# ── 6 · Push config to the VPS ────────────────────────────────────────────
stage "Configure the lead service" 2
say "Writing the three values to /opt/fein-leads/.env on the VPS and"
say "restarting the service."
if confirm "Write config to $VPS and restart fein-leads?"; then
  printf 'RESEND_API_KEY=%s\nCAL_LINK=%s\nCALCOM_WEBHOOK_SECRET=%s\nNOTIFY_TO=team@commixcapital.com\nMAIL_FROM=Daniel at fein <daniel@fein.vc>\n' \
    "$RESEND_API_KEY" "$CAL_LINK" "$CALCOM_WEBHOOK_SECRET" \
    | vps 'cat > /opt/fein-leads/.env && chmod 600 /opt/fein-leads/.env && systemctl restart fein-leads'
  sleep 1
  HEALTH=$(vps 'curl -s http://127.0.0.1:8787/health' || echo '{}')
  if [[ "$HEALTH" == *'"missingConfig":[]'* ]]; then
    printf '  %s✓ service healthy, no missing config%s\n' "$GREEN" "$RESET"
  else
    warn "service reports: $HEALTH"
  fi
else
  SKIPPED+=("VPS config push — re-run the wizard to finish")
fi
pause

# ── 7 · GitHub Pages HTTPS ────────────────────────────────────────────────
stage "fein.vc goes live" 3
say "Once the A records propagate, GitHub Pages serves the site."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if gh api -X PUT repos/clippycommits/fein-site/pages --field https_enforced=true >/dev/null 2>&1; then
    printf '  %s✓ HTTPS enforcement enabled via gh%s\n' "$GREEN" "$RESET"
  else
    warn "couldn't enforce HTTPS yet (cert may not be issued) — check the dashboard:"
    open_url "https://github.com/clippycommits/fein-site/settings/pages"
    step "Wait for the fein.vc green check + certificate, then tick 'Enforce HTTPS'."
  fi
else
  open_url "https://github.com/clippycommits/fein-site/settings/pages"
  step "Wait for the fein.vc green check + certificate, then tick 'Enforce HTTPS'."
fi
pause "Press Enter to continue."

# ── 8 · FormSubmit fallback activation ────────────────────────────────────
stage "FormSubmit fallback" 2
say "If the lead service is ever down, the form falls back to FormSubmit,"
say "which emails the lead to team@commixcapital.com. It needs one click."
open_url "https://mail.google.com/"
step "In the team@commixcapital.com inbox, find the FormSubmit activation"
say "  email and click Activate. (Nothing arrives until it's activated.)"
pause "Activated (or already was)? Press Enter."

# ── 9 · Smoke test the funnel ─────────────────────────────────────────────
stage "Smoke test" 5
say "End to end, with you as the lead."
if curl -fsS --max-time 10 https://api.fein.vc/health >/dev/null 2>&1; then
  printf '  %s✓ https://api.fein.vc is up (TLS working)%s\n' "$GREEN" "$RESET"
else
  warn "api.fein.vc not reachable over HTTPS yet — DNS may still be propagating."
  warn "Re-run this stage later; testing via the VPS directly for now."
fi
ask TEST_EMAIL "Your email for the test lead (you'll get the welcome email):"
if confirm "Send a test enquiry for $TEST_EMAIL now?"; then
  PAYLOAD=$(printf '{"email":"%s","first":"Test","last":"Lead","fund":"Wizard Test","size":"Under $50M"}' "$TEST_EMAIL")
  if curl -fsS --max-time 10 -X POST https://api.fein.vc/enquiry -H 'content-type: application/json' -d "$PAYLOAD" 2>/dev/null \
     || printf '%s' "$PAYLOAD" | vps "curl -fsS -X POST http://127.0.0.1:8787/enquiry -H 'content-type: application/json' -d @-"; then
    printf '\n  %s✓ enquiry accepted%s\n' "$GREEN" "$RESET"
    step "Check $TEST_EMAIL for the welcome email with the booking button."
    step "Check team@commixcapital.com for the lead notification."
    step "Optional full check: book a slot from the email — you should get a"
    say "  'fein call booked' notification, and the 3-day nudge is cancelled."
    note "Delete the test booking in cal.com afterwards."
  else
    warn "enquiry failed — check: ssh $VPS journalctl -u fein-leads -n 20"
  fi
fi
pause "Press Enter to finish."

finish
note "Funnel: form → instant booking email + your notification → 3-day nudge"
note "auto-cancelled on booking. Leads log: ssh $VPS cat /opt/fein-leads/leads.jsonl"
