#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
TOTAL_STAGES=10
TOTAL_MINUTES=45

# Values are remembered here between runs (Enter keeps a saved value); at
# stage 8 you copy them into Vercel's env settings.
mkdir -p "$HOME/.config/fein"
ENV_FILE="$HOME/.config/fein/funnel.env"

VPS="root@167.88.38.87"

banner "fein on Vercel — site + booking funnel"

# ── 1 · Vercel project ────────────────────────────────────────────────────
stage "Vercel — import the repo" 5
say "One project serves the site and the /api lead functions."
open_url "https://vercel.com/new"
step "Sign up / log in with the clippycommits GitHub account."
step "Import clippycommits/fein-site."
step "Framework preset: 'Other'. Leave Build Command and Output Directory"
say "  EMPTY (the site is prebuilt, static files live at the repo root)."
step "Deploy. When it finishes, open the *.vercel.app URL it gives you and"
say "  check /api/health on it — you should see JSON with missingConfig."
pause "Deployed and /api/health answers? Press Enter."

# ── 2 · Domain → Vercel ───────────────────────────────────────────────────
stage "fein.vc points at Vercel" 6
say "Vercel shows the exact DNS records; Namecheap holds them."
open_url "https://vercel.com/dashboard"
step "Project → Settings → Domains → Add: fein.vc (accept its suggestion to"
say "  redirect www.fein.vc to it)."
step "Vercel now shows the required records (an A for @ and a CNAME for www)."
open_url "https://ap.www.namecheap.com/domains/list/"
step "In Namecheap: fein.vc → Manage → Advanced DNS. DELETE the 'URL Redirect"
say "  Record' on @ and the CNAME on www pointing at parkingpage.namecheap.com."
step "ADD the A and CNAME records exactly as Vercel showed them."
warn "Leave the MX (smtp.google.com) and google-site-verification TXT alone."
step "Back in Vercel Domains, wait for the checkmarks (minutes to ~1h)."
pause "Records added? Press Enter (verification can finish in the background)."

# ── 3 · Upstash Redis ─────────────────────────────────────────────────────
stage "Upstash — nudge state" 4
say "Functions keep no disk, so the 'cancel the 3-day nudge when they book'"
say "state lives in a free Upstash Redis. You already have an account."
open_url "https://console.upstash.com/redis"
step "Create Database → name 'fein-leads', region close to your users, free"
say "  tier → Create."
step "On the database page, find the REST API section: copy the"
say "  UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN."
ask UPSTASH_REDIS_REST_URL "Paste the REST URL:"
ask_secret UPSTASH_REDIS_REST_TOKEN "Paste the REST token:"
write_env UPSTASH_REDIS_REST_URL "$UPSTASH_REDIS_REST_URL"
write_env UPSTASH_REDIS_REST_TOKEN "$UPSTASH_REDIS_REST_TOKEN"

# ── 4 · Resend domain ─────────────────────────────────────────────────────
stage "Resend — add the sending domain" 7
say "Emails go out as daniel@fein.vc, so Resend must verify the domain."
open_url "https://resend.com/domains"
step "Log in (same account as Cereal Milk is fine) → Add Domain → fein.vc."
step "Pick the region closest to you, then Resend shows three DNS records"
say "  (an MX and a TXT on 'send', and a resend._domainkey TXT)."
step "Copy each into Namecheap Advanced DNS EXACTLY as shown — host and"
say "  value both. They live on subdomains, so Google mail is untouched."
step "Back in Resend, press 'Verify DNS Records'. 'Pending' is fine for now."
pause "Records added and verification started? Press Enter."

# ── 5 · Resend API key ────────────────────────────────────────────────────
stage "Resend — API key" 2
open_url "https://resend.com/api-keys"
step "Create API Key → name 'fein-leads', permission 'Sending access',"
say "  domain fein.vc → Create. Copy the key (shown once, starts re_)."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
write_env RESEND_API_KEY "$RESEND_API_KEY"

# ── 6 · cal.com event type ────────────────────────────────────────────────
stage "cal.com — your booking page" 8
say "This is the link every email and the site's success screen point at."
open_url "https://app.cal.com/signup"
step "Sign up (or log in) — the free plan does everything we need."
step "Set your availability (Availability → working hours)."
step "Event Types → New: title 'fein intro', 30 minutes, add Google Meet or"
say "  whatever you prefer as the location."
step "Copy the event's public link (looks like https://cal.com/<you>/fein-intro)."
ask CAL_LINK "Paste the booking link:"
write_env CAL_LINK "$CAL_LINK"

# ── 7 · cal.com webhook ───────────────────────────────────────────────────
stage "cal.com — booking webhook" 4
CALCOM_WEBHOOK_SECRET=$(_existing CALCOM_WEBHOOK_SECRET || true)
if [[ -z "$CALCOM_WEBHOOK_SECRET" ]]; then
  CALCOM_WEBHOOK_SECRET=$(openssl rand -hex 24)
  write_env CALCOM_WEBHOOK_SECRET "$CALCOM_WEBHOOK_SECRET"
fi
say "When someone books, cal.com tells the function so the 3-day nudge is"
say "cancelled. The signing secret below was generated for you."
open_url "https://app.cal.com/settings/developer/webhooks/new"
step "Subscriber URL:  https://fein.vc/api/webhooks/calcom"
step "Event triggers:  tick 'Booking created' only."
step "Secret — paste exactly this:"
printf '\n      %s%s%s\n\n' "$BOLD" "$CALCOM_WEBHOOK_SECRET" "$RESET"
step "Save the webhook."
pause "Webhook saved? Press Enter."

# ── 8 · Vercel environment variables ──────────────────────────────────────
stage "Vercel — environment variables" 5
say "Add these seven in Project → Settings → Environment Variables (all"
say "environments), then Deployments → ⋯ on the latest → Redeploy:"
printf '\n'
printf '      RESEND_API_KEY            = %s\n' "$RESEND_API_KEY"
printf '      CAL_LINK                  = %s\n' "$CAL_LINK"
printf '      CALCOM_WEBHOOK_SECRET     = %s\n' "$CALCOM_WEBHOOK_SECRET"
printf '      NOTIFY_TO                 = team@commixcapital.com\n'
printf '      MAIL_FROM                 = Daniel at fein <daniel@fein.vc>\n'
printf '      UPSTASH_REDIS_REST_URL    = %s\n' "$UPSTASH_REDIS_REST_URL"
printf '      UPSTASH_REDIS_REST_TOKEN  = %s\n' "$UPSTASH_REDIS_REST_TOKEN"
printf '\n'
open_url "https://vercel.com/dashboard"
step "Paste each one, save, then REDEPLOY so the functions pick them up."
pause "Env vars saved and redeployed? Press Enter."

# ── 9 · FormSubmit fallback ───────────────────────────────────────────────
stage "FormSubmit fallback" 2
say "If the functions are ever unreachable, the form falls back to"
say "FormSubmit, which emails the lead to team@commixcapital.com."
open_url "https://mail.google.com/"
step "In the team@commixcapital.com inbox, find the FormSubmit activation"
say "  email and click Activate. (The fallback is dead until it's clicked.)"
pause "Activated (or already was)? Press Enter."

# ── 10 · Smoke test + retire the VPS service ──────────────────────────────
stage "Smoke test" 5
if HEALTH=$(curl -fsS --max-time 10 https://fein.vc/api/health 2>/dev/null); then
  if [[ "$HEALTH" == *'"missingConfig":[]'* ]]; then
    printf '  %s✓ https://fein.vc/api/health — config complete%s\n' "$GREEN" "$RESET"
  else
    warn "live but incomplete: $HEALTH"
  fi
else
  warn "fein.vc not answering yet — DNS may still be propagating. Re-run later."
fi
ask TEST_EMAIL "Your email for a test lead (you'll get the welcome email):"
if confirm "Send a test enquiry for $TEST_EMAIL now?"; then
  if curl -fsS --max-time 15 -X POST https://fein.vc/api/enquiry \
       -H 'content-type: application/json' \
       -d "{\"email\":\"$TEST_EMAIL\",\"first\":\"Test\",\"last\":\"Lead\",\"fund\":\"Wizard Test\"}"; then
    printf '\n  %s✓ enquiry accepted%s\n' "$GREEN" "$RESET"
    step "Check $TEST_EMAIL for the welcome email with the booking button."
    step "Check team@commixcapital.com for the lead notification."
    step "Optional full check: book a slot from the email — you should get a"
    say "  'fein call booked' notification, and the 3-day nudge is cancelled."
    note "Delete the test booking in cal.com afterwards."
  else
    warn "enquiry failed — check the function logs in the Vercel dashboard."
  fi
fi
if confirm "Retire the old VPS lead service (fein-leads + caddy on $VPS)?"; then
  ssh -o BatchMode=yes "$VPS" 'systemctl disable -q --now fein-leads caddy 2>/dev/null; echo retired' \
    && printf '  %s✓ VPS service retired%s\n' "$GREEN" "$RESET" \
    || SKIPPED+=("retire VPS service: ssh $VPS systemctl disable --now fein-leads caddy")
else
  SKIPPED+=("retire VPS service when comfortable: ssh $VPS systemctl disable --now fein-leads caddy")
fi
pause "Press Enter to finish."

finish
note "Funnel: form → instant booking email + your notification → 3-day nudge"
note "auto-cancelled on booking. Push to main = deploy. Health: fein.vc/api/health"
