// Icon pipeline: renders the fein graph mark into every raster icon the head
// and manifest reference. macOS-only tooling (qlmanage + sips), no ImageMagick.
//   node scripts/icons.mjs        -> writes favicon.ico, apple-touch-icon.png,
//                                    icon-192.png, icon-512.png, icon-512-maskable.png
// favicon.svg itself stays generated by src/build.js (theme-adaptive, transparent).
// Raster icons can't adapt to the tab theme, so they bake the dark tile: white
// mark on #000, which reads on both light and dark chrome.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const ROOT = path.join(path.dirname(new URL(import.meta.url).pathname), "..");
const TMP = fs.mkdtempSync(path.join(os.tmpdir(), "fein-icons-"));

// The mark from favicon.svg, centered in a 32-unit tile. bbox of the raw mark
// is x[3.4,26.9] y[5.4,27.6]; the transform recenters it and scales it into the
// tile with breathing room (scale per output: tab tiles tighter, maskable looser).
const mark = (scale) => `
<g transform="translate(16,16) scale(${scale}) translate(-15.15,-16.5)" stroke="#fff" fill="#fff">
<line x1="7" y1="24" x2="22" y2="9" stroke-width="2.4"/><line x1="22" y1="9" x2="24.5" y2="24" stroke-width="2.4"/>
<circle cx="7" cy="24" r="3.6"/><circle cx="22" cy="9" r="3.6"/><circle cx="24.5" cy="24" r="2.4"/>
</g>`;

const tile = (scale, radius) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<rect width="32" height="32" rx="${radius}" fill="#000"/>${mark(scale)}
</svg>`;

// qlmanage renders square SVGs 1:1 at -s (same trick as og.png in src/build.js)
function render(svg, name, size) {
  const src = path.join(TMP, name + ".svg");
  fs.writeFileSync(src, svg);
  execFileSync("qlmanage", ["-t", "-s", String(size), "-o", TMP, src], { stdio: "pipe" });
  const png = src + ".png";
  const out = path.join(TMP, `${name}-${size}.png`);
  fs.renameSync(png, out);
  return out;
}

function resize(png, size) {
  const out = png.replace(/-\d+\.png$/, `-${size}.png`);
  execFileSync("sips", ["-z", String(size), String(size), png, "--out", out], { stdio: "pipe" });
  return out;
}

// ICO container with PNG-encoded entries (all modern browsers + Google's
// favicon crawler read these; 16/32/48 is the set Google asks for).
function packIco(pngPaths, outPath) {
  const entries = pngPaths.map((p) => ({ data: fs.readFileSync(p) }));
  for (const e of entries) {
    e.w = e.data.readUInt32BE(16); // IHDR width
    e.h = e.data.readUInt32BE(20);
  }
  const header = Buffer.alloc(6);
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(entries.length, 4);
  let offset = 6 + 16 * entries.length;
  const dirs = entries.map((e) => {
    const d = Buffer.alloc(16);
    d.writeUInt8(e.w >= 256 ? 0 : e.w, 0);
    d.writeUInt8(e.h >= 256 ? 0 : e.h, 1);
    d.writeUInt16LE(1, 4); // planes
    d.writeUInt16LE(32, 6); // bpp
    d.writeUInt32LE(e.data.length, 8);
    d.writeUInt32LE(offset, 12);
    offset += e.data.length;
    return d;
  });
  fs.writeFileSync(outPath, Buffer.concat([header, ...dirs, ...entries.map((e) => e.data)]));
}

// Tab favicon: rounded dark tile, mark at .8 (48px master, sips down to 32/16)
const fav48 = render(tile(0.8, 6), "fav", 48);
packIco([resize(fav48, 16), resize(fav48, 32), fav48], path.join(ROOT, "favicon.ico"));

// apple-touch-icon: iOS masks its own corners, so square tile, slightly airier
fs.copyFileSync(render(tile(0.72, 0), "apple", 180), path.join(ROOT, "apple-touch-icon.png"));

// PWA icons: any-purpose pair + a maskable (mark inside the 40%-radius safe zone)
fs.copyFileSync(render(tile(0.72, 0), "pwa", 192), path.join(ROOT, "icon-192.png"));
fs.copyFileSync(render(tile(0.72, 0), "pwa", 512), path.join(ROOT, "icon-512.png"));
fs.copyFileSync(render(tile(0.52, 0), "mask", 512), path.join(ROOT, "icon-512-maskable.png"));

fs.rmSync(TMP, { recursive: true, force: true });
console.log("icons written:", ["favicon.ico", "apple-touch-icon.png", "icon-192.png", "icon-512.png", "icon-512-maskable.png"].join(", "));
