// Raster pipeline: turns the fein tile into every bitmap the head, the manifest,
// the link preview and an email signature need. macOS-only tooling (qlmanage +
// sips), no ImageMagick.
// Sources (all in src/):
//   logo.png  the master, as the brand was supplied: 1080x1080, #EF0000, white
//             "fein". The square icons and the email PNGs are straight resizes.
//   logo.svg  the same tile as a font-free vector (scripts/logo-svg.py), for the
//             renders that change the tile: favicon.ico rounds the corners, the
//             maskable icon shrinks the mark into the 40%-radius safe zone.
//             1200x1200 canvas with the 1200x630 card centered, cropped here.
// favicon.svg and logo.svg at the root stay generated by src/build.js.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const ROOT = path.join(path.dirname(new URL(import.meta.url).pathname), "..");
const SRC = path.join(ROOT, "src");
const TMP = fs.mkdtempSync(path.join(os.tmpdir(), "fein-icons-"));

const master = path.join(SRC, "logo.png");
const logoSvg = fs.readFileSync(path.join(SRC, "logo.svg"), "utf8");
const markPath = (logoSvg.match(/<path[^>]*\/>/) || [])[0];
const red = (logoSvg.match(/<rect[^>]*fill="(#[0-9A-Fa-f]{6})"/) || [])[1];
if (!markPath || !red) throw new Error("src/logo.svg: tile rect or wordmark path not found");

// the tile, optionally with rounded corners and the wordmark scaled about the center
const tile = (radius, scale) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1080 1080">
<rect width="1080" height="1080" rx="${radius}" fill="${red}"/>
<g transform="translate(540,540) scale(${scale}) translate(-540,-540)">${markPath}</g>
</svg>`;

// qlmanage renders square SVGs 1:1 at -s
function render(svg, name, size) {
  const src = path.join(TMP, name + ".svg");
  fs.writeFileSync(src, svg);
  execFileSync("qlmanage", ["-t", "-s", String(size), "-o", TMP, src], { stdio: "pipe" });
  const out = path.join(TMP, `${name}-${size}.png`);
  fs.renameSync(src + ".png", out);
  return out;
}

function resize(png, size, out) {
  out = out || png.replace(/-\d+\.png$/, `-${size}.png`);
  execFileSync("sips", ["-z", String(size), String(size), png, "--out", out], { stdio: "pipe" });
  return out;
}

// ICO container with PNG-encoded entries (all modern browsers + Google's
// favicon crawler read these; 16/32/48 is the set Google asks for).
function packIco(pngPaths, outPath) {
  const entries = pngPaths.map((p) => ({ data: fs.readFileSync(p) }));
  for (const e of entries) {
    e.w = e.data.readUInt32BE(16); // IHDR width
    e.h = e.data.readUInt32BE(20);
  }
  const header = Buffer.alloc(6);
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(entries.length, 4);
  let offset = 6 + 16 * entries.length;
  const dirs = entries.map((e) => {
    const d = Buffer.alloc(16);
    d.writeUInt8(e.w >= 256 ? 0 : e.w, 0);
    d.writeUInt8(e.h >= 256 ? 0 : e.h, 1);
    d.writeUInt16LE(1, 4); // planes
    d.writeUInt16LE(32, 6); // bpp
    d.writeUInt32LE(e.data.length, 8);
    d.writeUInt32LE(offset, 12);
    offset += e.data.length;
    return d;
  });
  fs.writeFileSync(outPath, Buffer.concat([header, ...dirs, ...entries.map((e) => e.data)]));
}

// Square tiles straight off the master: PWA icons, the iOS icon (iOS masks its
// own corners) and the two email-signature sizes (512 for retina, 128 to drop in)
resize(master, 180, path.join(ROOT, "apple-touch-icon.png"));
resize(master, 512, path.join(ROOT, "logo.png"));
resize(master, 128, path.join(ROOT, "logo-128.png"));

// Tab favicon: 12% rounded corners like favicon.svg (48px master, sips down to 32/16)
const fav48 = render(tile(130, 1), "fav", 48);
packIco([resize(fav48, 16), resize(fav48, 32), fav48], path.join(ROOT, "favicon.ico"));



fs.rmSync(TMP, { recursive: true, force: true });
console.log("written:", ["favicon.ico", "apple-touch-icon.png", "logo.png", "logo-128.png"].join(", "));
