#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
TOTAL_STAGES=13
TOTAL_MINUTES=60

# Values are remembered here between runs (Enter keeps a saved value).
mkdir -p "$HOME/.config/fein"
ENV_FILE="$HOME/.config/fein/intercom.env"

# One link everywhere, tagged so chat bookings are separable from /demo form
# bookings in cal.com.
CAL_CHAT="https://cal.com/daniel-hull-tezr2c/fein-intro?utm_source=chat"
REPO="$HOME/github/fein/fein-landing"

banner "Intercom for fein — sales capture + delivery, end to end"

# ── 1 · Workspace basics ──────────────────────────────────────────────────
stage "Workspace — name, logo, timezone" 4
say "Every surface a visitor sees inherits these."
note "If any settings page has moved, the search box at the top of Settings"
note "finds it by name."
open_url "https://app.intercom.com/a/apps/i91a73cr/settings"
step "Settings → Workspace → General: set the workspace name to exactly"
say "  'fein' (lowercase, as the site writes it)."
step "Upload the logo where the workspace asks for one:"
say "  $REPO/icon-512.png"
step "Set the workspace timezone to yours."
pause "Name, logo and timezone saved? Press Enter."

# ── 2 · Your teammate profile ─────────────────────────────────────────────
stage "Your profile — the human behind the chat" 2
say "Replies you send show this face and name, so make it real."
open_url "https://app.intercom.com/a/apps/i91a73cr/settings"
step "Click your avatar (bottom left) → Your profile."
step "Name: 'Daniel'. Photo: upload ~/Desktop/daniel-intercom-avatar.jpg"
say "  (512px crop already prepared)."
pause "Profile saved? Press Enter."

# ── 3 · Messenger appearance ──────────────────────────────────────────────
stage "Messenger — styling, intro, privacy" 5
say "The launcher itself is the site's own (white pill, already live), so"
say "only the open panel is styled here."
open_url "https://app.intercom.com/a/apps/i91a73cr/settings"
step "Settings → Channels → Messenger (the Web section)."
step "Styling: action color and background color #0070F3 (the site's blue),"
say "  or black #08090A if the blue looks loud against the dark panel."
warn "Do NOT enable the standard launcher — the site hides it on purpose"
say "  and shows its own. Leave launcher visibility off for web."
step "Intro / greeting text:"
printf '\n      %sAsk us anything about fein.%s\n\n' "$BOLD" "$RESET"
step "Data & privacy: enable the consent notice and point the privacy"
say "  policy link at https://fein.vc/privacy"
pause "Messenger styled? Press Enter."

# ── 4 · Office hours + reply expectations ─────────────────────────────────
stage "Office hours — when 'the team is online' is true" 3
say "Away copy, reply-time promises and Fin handoffs all key off this."
open_url "https://app.intercom.com/a/apps/i91a73cr/settings"
step "Settings → Workspace → Office hours: set your real working hours."
step "Where the Messenger asks what reply time to show, pick"
say "  'usually replies in a few minutes' (only shown inside office hours)."
pause "Hours set? Press Enter."

# ── 5 · Fin — identity and what it knows ──────────────────────────────────
stage "Fin — fein branding + content it answers from" 6
say "Fin stays visibly an AI (no pretending it is a person), but it wears"
say "fein's name and mark, and it answers from the site's own pages."
open_url "https://app.intercom.com/a/apps/i91a73cr/settings"
step "Settings → AI & Automation → Fin AI Agent → Fin's identity:"
say "  Name: 'fein AI'. Avatar: hover it and upload icon-512.png."
step "Keep the 'AI Agent' label ON. Honesty is the brand here."
step "Now give it content: AI & Automation → Knowledge (or 'Content')."
step "Add website sync for https://fein.vc — it crawls the pages. Check"
say "  /pricing, /self-host, /deploy and /pe are included."
note "fein.vc/llms-full.txt is the whole site as text if you would rather"
note "paste one document than sync."
pause "Fin renamed and fed? Press Enter."

# ── 6 · Workflow — welcome + lead capture ─────────────────────────────────
stage "Workflow — the sales flow" 8
say "This is the money stage: every engaged visitor leaves an email or"
say "books a call."
open_url "https://app.intercom.com/a/apps/i91a73cr/automation/workflows"
step "Open (or create) the workflow that fires when a visitor opens the"
say "  Messenger / sends their first message. Build these blocks in order:"
say ""
say "  1. Message:"
printf '\n      %sHey 👋 This is the fein team. Ask us anything about fein:\n      how it works, pricing, security, or what deployment looks\n      like at your firm.%s\n\n' "$BOLD" "$RESET"
say "  2. Message, with a button linking to the calendar:"
printf '\n      %sIf you would rather just see it, grab 20 minutes with us and\n      we will run fein on your firm'\''s own use case live.%s\n' "$BOLD" "$RESET"
printf '      %sbutton link: %s%s\n\n' "$DIM" "$CAL_CHAT" "$RESET"
step "3. 'Collect visitor email' step, firing after their first message:"
printf '\n      %sLeave your email so our reply reaches you if you step away.%s\n\n' "$BOLD" "$RESET"
say "  4. Message (the qualifier — it makes every answer specific):"
printf '\n      %sWhat CRM are you on, and roughly what fund size? The more\n      you tell us, the more useful our answer will be.%s\n\n' "$BOLD" "$RESET"
step "5. Then 'Let Fin answer', with handoff to the team on request or"
say "  when Fin cannot answer."
step "Sender for the message blocks: the workspace / fein AI, not a named"
say "  teammate. The team framing is the honest one."
pause "Workflow built and set live? Press Enter."

# ── 7 · Workflow — out of hours ───────────────────────────────────────────
stage "Workflow — the away branch" 3
say "Same workflow, one branch on office hours."
step "Add a branch: outside office hours → Message:"
printf '\n      %sThe team is offline right now. Leave your question and your\n      email and we will reply first thing. Or pick a time that suits\n      you and it goes straight in the calendar.%s\n' "$BOLD" "$RESET"
printf '      %sbutton link: %s%s\n\n' "$DIM" "$CAL_CHAT" "$RESET"
step "Fin still answers in this branch; the email step already ran."
pause "Away branch added? Press Enter."

# ── 8 · Proactive message ─────────────────────────────────────────────────
stage "Outbound — the proactive chat" 4
say "Fires once per visitor after ~30s. The site launcher already shows a"
say "red unread dot when it lands; Intercom draws the preview bubble."
open_url "https://app.intercom.com/a/apps/i91a73cr/outbound/all"
step "New message → Chat. Copy:"
printf '\n      %s👋 Curious whether fein fits your stack? Tell us your CRM and\n      we will show you exactly how it plugs in. Or grab 20 minutes\n      with the team.%s\n\n' "$BOLD" "$RESET"
step "Sender: Daniel (it really is you replying — a face earns the reply)."
step "Audience: everyone on fein.vc who is NOT a user/customer."
step "Trigger: 30 seconds on the page. Frequency: once per person."
pause "Proactive message live? Press Enter."

# ── 9 · Email — authenticate the sending domain ───────────────────────────
stage "Email — DKIM for Intercom mail" 6
say "Chat replies to captured emails go out as email. Unauthenticated,"
say "they land in spam, which unwinds stage 6."
open_url "https://app.intercom.com/a/apps/i91a73cr/settings"
step "Settings → Channels → Email → Domains: add fein.vc and follow its"
say "  DKIM setup. Intercom shows CNAME records on subdomains."
open_url "https://ap.www.namecheap.com/domains/list/"
step "Add those CNAMEs in Namecheap → fein.vc → Advanced DNS."
warn "ADD only. The existing SPF/DMARC TXT records on @ and _dmarc, the MX,"
say "  and Google/Resend DKIM records stay exactly as they are — Intercom's"
say "  records live on their own subdomains and do not collide."
step "Back in Intercom, verify the domain. Set the sender address to"
say "  team@fein.vc (or daniel@fein.vc if you want every mail personal)."
pause "Domain verified green? Press Enter."

# ── 10 · Email — replies reach the inbox they left ────────────────────────
stage "Email — continuation settings" 3
say "The point of capturing an email is that the thread follows them out."
open_url "https://app.intercom.com/a/apps/i91a73cr/settings"
step "In the Email / Messenger settings, make sure replying by email is"
say "  enabled for visitors who left an address (reply notifications with"
say "  full message content, not just 'you have a reply')."
step "Check the notification email template shows the fein name and logo"
say "  from stage 1."
pause "Continuation on? Press Enter."

# ── 11 · Macros — the delivery-side answers ───────────────────────────────
stage "Macros — saved replies for the inbox" 5
say "Four answers cover most first conversations. Saved once, reused"
say "forever, and they keep the voice consistent."
open_url "https://app.intercom.com/a/apps/i91a73cr/settings"
step "Settings → Inbox (or Helpdesk) → Macros. Create four:"
say ""
say "  'pricing' —"
printf '\n      %sRunning fein yourself is free forever, the code is Apache 2.0.\n      Managed setup is $5,000 once, then from $1,000 a month priced\n      on fund size, never per seat. The full comparison:\n      https://fein.vc/pricing%s\n\n' "$BOLD" "$RESET"
say "  'security' —"
printf '\n      %sfein runs on your own servers, on code you can read. Your data\n      never leaves your firm and nothing is sent to us. Details:\n      https://fein.vc/self-host%s\n\n' "$BOLD" "$RESET"
say "  'book' —"
printf '\n      %sEasiest is to see it live. Pick a time and we will run fein on\n      your firm'\''s own use case: %s%s\n\n' "$BOLD" "$CAL_CHAT" "$RESET"
say "  'self-host' —"
printf '\n      %sClone it and run it, free forever, no feature held back:\n      https://fein.vc/self-host. If you would rather we deploy and\n      run it for you: https://fein.vc/deploy%s\n\n' "$BOLD" "$RESET"
pause "Macros saved? Press Enter."

# ── 12 · Never miss a message ─────────────────────────────────────────────
stage "Notifications — phone + Slack" 4
say "'Usually replies in a few minutes' is a promise; these keep it."
step "Install the Intercom mobile app (App Store / Play Store), sign in,"
say "  allow notifications."
open_url "https://app.intercom.com/a/apps/i91a73cr/appstore"
step "Install the Slack app from the Intercom app store and point new-"
say "  conversation notifications at a #chat (or #sales) channel."
step "Your personal notification settings: notify on every new conversation"
say "  and every reply, email fallback on."
pause "Phone buzzing on new conversations? Press Enter."

# ── 13 · Smoke test ───────────────────────────────────────────────────────
stage "Smoke test — be your own lead" 5
say "A private window makes you an anonymous visitor."
step "Open https://fein.vc in a private window. Move the mouse, wait 30s:"
say "  the proactive preview should appear and the pill should show the"
say "  red unread dot."
step "Open the chat: welcome messages from 'fein', calendar button works"
say "  and lands on cal.com with utm_source=chat in the URL."
step "Send a message, leave a test email you own at the email step."
step "Phone + Slack should notify. Reply from the phone app."
step "Check the test email inbox: the reply arrived as authenticated"
say "  email (From shows fein, not via intercommail)."
step "Ask the chat a pricing question and check Fin answers from the site"
say "  content, labelled as AI."
pause "All green? Press Enter."

finish
say "The wire-up is done. Two numbers tell you if it works: emails captured"
say "in chat, and cal.com bookings with utm_source=chat."
