const fs = require("fs");
const path = require("path");

const SITE = "https://fein.vc";
const TITLE = "fein · the memory layer for venture capital";
// DESC: search-snippet length (~160 chars). DESC_LONG: link previews + JSON-LD.
// Both are written in Simplified Technical English, one idea to a sentence, and
// both hold the approved terms: "your team" for the customer, "context graph"
// for the structure, "source document" for provenance. Never swap in a synonym
// here, because these two strings are what an answer engine quotes back.
const DESC = "fein reads your team's email, calendar, notes, and CRM. It builds one context graph of every relationship your team has. It answers in Claude, ChatGPT, and Cursor.";
const DESC_LONG = "fein reads your team's email, calendar, notes, and CRM. It builds one context graph of every relationship your team has. It answers in Claude, ChatGPT, and Cursor. Each answer carries its source document. Self-hosted, open source, live in 14 days.";
const LASTMOD = "2026-08-15";
// The same date, written for humans. LASTMOD stays ISO for machines (sitemap,
// meta, JSON-LD, datetime attributes); the legal pages print this one in their
// visible "Last updated" line. Keep the two in step when the date moves.
const LASTMOD_HUMAN = "15 August 2026";

// ---- fonts ----
// The *.subset.woff2 files are generated by subset-fonts.py: the full faces are
// a 100-900 weight axis over the whole Latin set, and this site renders 128
// codepoints at the three weight ranges the @font-face descriptors already
// clamp to. Subsetting is therefore lossless and takes 101 KB of font down to
// 42 KB, which is a third of the wire weight of the page.
//
// The risk that buys is tofu: add a character the subset lacks and the browser
// falls back mid-word. assertCharsetCovers below closes that off by failing the
// BUILD instead, so the failure lands here and not on a visitor's screen.
const CHARSET = fs.readFileSync("fonts.charset.txt", "utf8").replace(/\n$/, "");
const sansB64 = fs.readFileSync("GeistSans.subset.woff2").toString("base64");
const monoB64 = fs.readFileSync("GeistMono.subset.woff2").toString("base64");
// Inter (variable 400-600, latin cut) carries body copy, sub headings, buttons
// and nav; Geist is the display face for h1 and h2 only.
const interB64 = fs.readFileSync("Inter.subset.woff2").toString("base64");
// Newsreader italic used to set the section labels here, cut against its own
// charset. The labels are small grey Inter now, so the face, its subset guard
// and its 6 KB of base64 are gone; Newsreader.subset.woff2 and
// fonts.serif.charset.txt are left on disk in case that voice comes back.

// Everything the page can actually render: element text, attributes that surface
// as text (alt/aria-label/title/placeholder/content), CSS content: strings, and
// string literals in the inline scripts. Deliberately over-inclusive -- a false
// alarm costs one character in fonts.charset.txt, a miss costs tofu in production.
function assertCharsetCovers(html, label) {
  const covered = new Set(Array.from(CHARSET));
  ["\n", "\r", "\t"].forEach(c => covered.add(c));
  const decoded = html
    .replace(/&middot;/g, "·").replace(/&minus;/g, "−")
    .replace(/&rarr;/g, "→").replace(/&larr;/g, "←")
    .replace(/&darr;/g, "↓").replace(/&uarr;/g, "↑")
    .replace(/&mdash;/g, "—").replace(/&ndash;/g, "–")
    .replace(/&hellip;/g, "…").replace(/&copy;/g, "©")
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(+d))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)));
  const missing = new Map();
  for (const ch of decoded) if (!covered.has(ch)) missing.set(ch, (missing.get(ch) || 0) + 1);
  if (missing.size) {
    const list = [...missing].map(([c, n]) => `U+${c.codePointAt(0).toString(16).toUpperCase().padStart(4, "0")} ${JSON.stringify(c)} x${n}`);
    throw new Error(
      `${label}: ${missing.size} codepoint(s) outside the font subset -- these would render as tofu:\n  ` +
      list.join("\n  ") + `\nAdd them to src/fonts.charset.txt and re-run subset-fonts.py.`);
  }
}

// ---- shared nav: defined once in fein.tpl.html between fein-nav markers,
// injected into every sub-page so the site cannot drift into per-page
// navigation again. The CSS slice rides along for the pages that carry their
// own reduced stylesheet (/demo and the legal pages); the rest inherit it
// through __STYLE__. ----
const tplSrc = fs.readFileSync("fein.tpl.html", "utf8");
function sliceBetween(src, a, b, label) {
  const i = src.indexOf(a), j = src.indexOf(b, i + a.length);
  if (i < 0 || j < 0) throw new Error("nav markers missing: " + label);
  return src.slice(i + a.length, j);
}
const NAV_HTML = sliceBetween(tplSrc, "<!--fein-nav:html:start-->", "<!--fein-nav:html:end-->", "html");
const NAV_CSS = sliceBetween(tplSrc, "/*fein-nav:css:start*/", "/*fein-nav:css:end*/", "css");
// Sub-pages live at /<slug>/, so the home-page section anchors gain the root
// path (href="#" dropdown triggers are left alone), and the page's own link is
// marked current. The nav repeats a link on up to three surfaces (bar,
// dropdown, mobile menu), so the replace is global: marking only the first
// match would leave the mobile menu's copy unmarked for screen readers.
function navFor(slug) {
  let nav = NAV_HTML.replace(/href="#(?=[a-z])/g, 'href="/#')
    .replace('href="/#home" aria-label="fein home"', 'href="/" aria-label="fein home"');
  if (slug) nav = nav.replace(new RegExp('(<a[^>]*href="/' + slug + '")', 'g'), '$1 aria-current="page"');
  return nav;
}
const NAV_STYLE_TAG = "<style>\n  :root{--nav-h:64px}\n" + NAV_CSS + "</style>";

// ---- inject fonts into shared body ----
let body = tplSrc
  .replace("__GEIST_SANS_B64__", sansB64)
  .replace("__GEIST_MONO_B64__", monoB64)
  .replace("__INTER_B64__", interB64);
if (body.indexOf("__GEIST") > -1 || body.indexOf("__INTER") > -1 || body.indexOf("__NEWSREADER") > -1) throw new Error("font placeholder left");

// ---- avatars: the three faces in the Slack thread mock in #memory ----
// Inlined like the fonts and the sprite, so the page stays one file. Sources,
// photographers and the crop numbers are in avatars/README.md. Anna Lindqvist
// posts twice, so these are replaceAll and not replace: a plain string replace
// takes the first match only and would have left a raw __AV_AL__ in the second
// message, which is the sort of thing that ships looking like nothing at all.
const AVATARS = { AV_DR: "avatars/dev-raman.webp", AV_MF: "avatars/marcus-feld.webp", AV_AL: "avatars/anna-lindqvist.webp", AV_DH: "avatars/daniel.webp" };
for (const [token, file] of Object.entries(AVATARS)) {
  if (!fs.existsSync(file)) throw new Error(`avatar missing: ${file} (see avatars/README.md)`);
  body = body.replaceAll(`__${token}__`, fs.readFileSync(file).toString("base64"));
}
if (/__AV_[A-Z]+__/.test(body)) throw new Error("avatar placeholder left");

// ---- brand-logo sprite (symbols referenced by <use href="#l-name">) ----
const LOGOS = { gmail: "logos/gmail.svg", gcal: "logos/gcal.svg", gdrive: "logos/gdrive.svg", attio: "logos/attio.svg", affinity: "logos/affinity.svg", linkedin: "logos/linkedin.svg", notion: "logos/notion.svg", slack: "logos/slack.svg", granola: "logos/granola.svg", claude: "logos/claude.svg", openai: "logos/openai.svg", cursor: "logos/si-cursor.svg", gemini: "logos/si-gemini.svg", perplexity: "logos/si-perplexity.svg", copilot: "logos/si-githubcopilot.svg", github: "logos/github.svg", salesforce: "logos/si-salesforce.svg", dropbox: "logos/si-dropbox.svg", box: "logos/si-box.svg", crunchbase: "logos/si-crunchbase.svg", googlesheets: "logos/si-googlesheets.svg", whatsapp: "logos/whatsapp.svg" };
const MONO = { openai: 1, cursor: 1, gemini: 1, perplexity: 1, copilot: 1, github: 1 }; // monochrome marks -> recolor via currentColor
function symbolFor(name, file) {
  let s = fs.readFileSync(file, "utf8").replace(/<\?xml[^>]*\?>/i, "").trim();
  const vb = (s.match(/viewBox="([^"]+)"/i) || [null, "0 0 24 24"])[1];
  // namespace internal ids so gradients/clips can't collide across logos
  Array.from(s.matchAll(/id="([^"]+)"/g)).map(m => m[1]).forEach(function (id) {
    const p = name + "_" + id;
    s = s.split('id="' + id + '"').join('id="' + p + '"')
         .split('url(#' + id + ')').join('url(#' + p + ')')
         .split('href="#' + id + '"').join('href="#' + p + '"')
         .split('xlink:href="#' + id + '"').join('xlink:href="#' + p + '"');
  });
  let inner = s.replace(/^[\s\S]*?<svg[^>]*>/i, "").replace(/<\/svg>\s*$/i, "");
  if (MONO[name]) inner = '<g fill="currentColor">' + inner.replace(/fill="[^"]*"/gi, "") + '</g>';
  return '<symbol id="l-' + name + '" viewBox="' + vb + '">' + inner + '</symbol>';
}
function spriteOf(names) {
  let s = '<svg width="0" height="0" style="position:absolute;width:0;height:0;overflow:hidden" aria-hidden="true">';
  names.forEach(function (k) { s += symbolFor(k, LOGOS[k]); });
  return s + '</svg>';
}
// The sprite used to sit whole between <body> and the hero, which put ~22 KB of
// below-the-fold SVG in front of the <h1> in the byte stream. On a throttled
// connection first paint then landed with .wrap half-built and the hero grew
// under it: a measured CLS of 0.0635 on 2-in-8 to 7-in-8 loads, depending
// entirely on where the chunk boundary fell. Splitting it takes that to 0/44
// and pulls first paint ~40-56 ms earlier, for no change in bytes sent.
//
// Only the GitHub mark is above the fold (the hero's "Use it for free" button),
// so it stays; the other fifteen are first referenced in #change and below, and
// ride at the end of <body> where they cost the hero nothing.
// The hero carries the picture now: five source documents, the three assistants
// the answer can be asked in, and the citation on every claim. All of those
// marks paint above the fold, so they ship in the head sprite rather than the
// end-of-body one. The guard below is what tells you when this list is stale.
const SPRITE_EARLY = ["github", "gmail", "granola", "linkedin", "gcal", "affinity", "slack", "claude", "openai", "cursor", "whatsapp"];
const spriteHero = spriteOf(SPRITE_EARLY);
const spriteRest = spriteOf(Object.keys(LOGOS).filter(k => SPRITE_EARLY.indexOf(k) < 0));

// Guard the split: a mark used in the hero but defined at the end of the body
// renders as an empty box until the document finishes streaming, which is worse
// than the layout shift this change removes. Fail the build instead.
const heroMarkup = (body.match(/<section id="home"[\s\S]*?<\/section>/) || [""])[0];
const heroRefs = [...new Set(Array.from(heroMarkup.matchAll(/href="#l-([a-z]+)"/g), m => m[1]))];
const late = heroRefs.filter(r => SPRITE_EARLY.indexOf(r) < 0);
if (late.length) throw new Error(
  "logo(s) used in the hero but only defined in the end-of-body sprite: " + late.join(", ") +
  "\nAdd them to SPRITE_EARLY in build.js, or the hero will paint an empty icon while the page streams.");

body = body.replace("__LOGO_SPRITE__", spriteHero);
if (body.indexOf("__LOGO_SPRITE__") > -1) throw new Error("logo sprite placeholder left");

// artifact version = body only (claude.ai wraps head/body), so it carries both halves
fs.writeFileSync("fein-landing.html", body + spriteRest);

// ---- split <style> out to head for the standalone doc ----
const sEnd = body.indexOf("</style>") + "</style>".length;
const styleBlock = body.slice(0, sEnd);
const rest = body.slice(sEnd);

// ---- FAQ: no longer a section on the page. It stays here for llms.txt only,
// which is why there is no FAQPage in the JSON-LD: that markup requires the
// answers to be visible on the page it is served from. ----
const faqs = [
  ["What exactly is fein?", "fein is your firm's memory layer. It reads your email, calendar, notes, and CRM. It resolves them into one context graph. It answers over MCP in Claude, ChatGPT, and Cursor. It is not a CRM that you fill in. It maintains itself."],
  ["How is this different from Affinity or Attio?", "A CRM is a database that your team fills in by hand. fein reads your CRM and everything around it. It resolves this into one graph. The graph stays current automatically. fein answers where your team already works. It sits on top of the CRM. It needs no new data entry."],
  ["What does it cost?", "It costs $5,000 once to build it into your stack. Then you pick a monthly plan set by how much we keep doing: Core is $250 each month, Plus is $500, and Pro is $750. An annual plan, paid in advance, costs 15% less. There is no per-seat pricing. Running it yourself is free forever."],
  ["Can't we build this ourselves?", "Yes. It is open source, so you can clone it. The monthly fee pays for the engineer who keeps it current. Then your engineer can build on top of it."],
  ["What happens if we cancel?", "Nothing stops. It runs on your servers. The graph, the connectors, and every answer stay yours."],
  ["How long does setup take?", "Fourteen days. The date is a commitment. Your part is two short calls. We do everything between them."],
  ["Is our data safe?", "Your data never leaves your infrastructure. fein checks access for each person. Every line of code is open to audit."],
  ["What does it connect to?", "It connects to Gmail, Google Calendar, Drive, LinkedIn, Attio, Affinity, and Granola. Answers appear in Claude, ChatGPT, Gemini, and Cursor. We add new connectors often."]
];

// feature list mirrors the visible #features + #how copy; AI answer engines read this verbatim
const FEATURES = [
  "Warm introduction paths: the weighted shortest path to a founder, an LP, or an operator, and the best person to make the introduction",
  "Meeting briefs: the attendees, how you know each of them, and what was open, from your calendar and inbox, before the meeting starts",
  "Deal memory: every company you saw, the memo, and the exact reason you passed, with each line traced to its source document",
  "Cadence alerts: relationships that drift from their learned rhythm, flagged before they go cold",
  "Entity resolution: every duplicate contact across your tools resolved to one identity, scored from real signals, not an LLM guess",
  "One MCP endpoint: the same cited answer in Claude, ChatGPT, Gemini, and Cursor, from structured graph traversal, not document scraping"
];

// ---- the film (#memory) ----
// 622 frames at 24 fps is 25.916s; PT26S matches the h2 on the page, so the
// markup and the visible copy tell a crawler the same thing. contentUrl points
// at the H.264 cut rather than the AV1 webm because it is the one every crawler
// and every browser can actually decode.
//
// The transcript matters more than the rest of this object put together: the
// film's entire positioning argument is 55 words that exist only as pixels and
// as an audio track, which is to say it is invisible to every search engine and
// every AI assistant that has ever looked at this page. It is transcribed from
// the narration (see video/fein-demo.en.vtt, which carries the same words with
// timings). Since the on-page transcript was removed, this property and that
// .vtt are the only places the narration exists as text.
const VIDEO_NAME = "fein in twenty-six seconds";
const VIDEO_DESC = "A short walkthrough of fein: a partner asks who the warmest path into a company is and what the firm said when it passed, and fein answers with citations from seven documents across four sources, then shows the memory behind the answer and the eight systems it reads.";
const VIDEO_TRANSCRIPT = "Introducing fein. Privacy-first, open-source, agentic memory layer, purpose-built for venture capital. Humans and agents can speak with fein to query and understand facts over time. Team members draw from the same system of record: a single endpoint for all of your AI agents to query and understand your VC's knowledge base.";
const VIDEO_UPLOADED = "2026-08-11";

// ---- the offer catalogue, stated once. These are the numbers the visible
// pricing copy makes: $0 to run it yourself, $5,000 for the managed setup,
// then Core/Plus/Pro monthly. They ride in the SoftwareApplication node on
// every page whose visible copy states them (/, /pricing, /deploy,
// /self-host), so an answer engine reads the prices as data instead of
// parsing a table. Change a price on the page and it must change here too.
const REPO_URL = "https://github.com/clippycommits/fein";
const OFFER_SELF_HOST = {
  "@type": "Offer", "@id": SITE + "/self-host#offer", name: "Self-hosted, free",
  description: "Clone the repository and run fein yourself for nothing, forever. Apache 2.0 licensed. There is no paid tier of the software and no feature held back to make one.",
  url: SITE + "/self-host", price: "0", priceCurrency: "USD",
  availability: "https://schema.org/InStock"
};
const OFFER_MANAGED = {
  "@type": "Offer", "@id": SITE + "/deploy#offer", name: "Managed setup",
  description: "A forward deployed engineer builds fein into the firm's stack: connects every source, resolves duplicate people, reads the full history back, and hands over a working graph on day 14. $5,000 once, then a monthly plan.",
  url: SITE + "/deploy", price: "5000", priceCurrency: "USD",
  availability: "https://schema.org/InStock"
};
function monthlyOffer(plan, monthly, adds) {
  return {
    "@type": "Offer", "@id": SITE + "/pricing#" + plan.toLowerCase(), name: plan + " plan",
    description: adds, url: SITE + "/pricing",
    availability: "https://schema.org/InStock",
    priceSpecification: { "@type": "UnitPriceSpecification", price: monthly, priceCurrency: "USD", billingIncrement: 1, unitText: "month" }
  };
}
const OFFERS_MONTHLY = [
  monthlyOffer("Core", 250, "Connectors repaired after upstream API changes, updates and security patches applied, email support. Never per seat."),
  monthlyOffer("Plus", 500, "Everything in Core, plus new answers built on request, a quarterly graph review, priority support. Never per seat."),
  monthlyOffer("Pro", 750, "Everything in Plus, plus new connectors built for new tools, a named engineer, same-day support. Never per seat.")
];
const OFFERS_ALL = [OFFER_SELF_HOST, OFFER_MANAGED].concat(OFFERS_MONTHLY);

const ld = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "VideoObject", "@id": SITE + "/#demo-film",
      name: VIDEO_NAME, description: VIDEO_DESC,
      contentUrl: SITE + "/video/fein-demo-1440.mp4",
      thumbnailUrl: [SITE + "/video/fein-demo-poster.jpg"],
      uploadDate: VIDEO_UPLOADED, duration: "PT26S",
      width: 2560, height: 1440, encodingFormat: "video/mp4",
      inLanguage: "en", isFamilyFriendly: true,
      transcript: VIDEO_TRANSCRIPT,
      // the timed captions exist as a real file for machines that want them.
      // Deliberately not wired up as a <track>: Safari and Chromium force-enable
      // caption tracks for readers who have captions on at the OS level, and this
      // film already carries its captions burned into the picture.
      caption: {
        "@type": "MediaObject", contentUrl: SITE + "/video/fein-demo.en.vtt",
        encodingFormat: "text/vtt", inLanguage: "en"
      },
      embedUrl: SITE + "/#memory",
      publisher: { "@id": SITE + "/#org" },
      isPartOf: { "@id": SITE + "/#webpage" },
      about: { "@id": SITE + "/#app" }
    },
    { "@type": "Organization", "@id": SITE + "/#org", name: "fein", alternateName: "Fein", url: SITE + "/", description: DESC_LONG, slogan: "the memory layer for venture capital", email: "sales@fein.vc", logo: SITE + "/icon-512.png", image: SITE + "/og.png", sameAs: [REPO_URL], knowsAbout: ["venture capital", "private equity", "limited partner relations", "relationship intelligence", "entity resolution", "knowledge graphs", "Model Context Protocol"], contactPoint: { "@type": "ContactPoint", contactType: "sales", email: "sales@fein.vc", url: SITE + "/demo" } },
    { "@type": "WebSite", "@id": SITE + "/#website", url: SITE + "/", name: "fein", description: DESC, inLanguage: "en", publisher: { "@id": SITE + "/#org" } },
    { "@type": "WebPage", "@id": SITE + "/#webpage", url: SITE + "/", name: TITLE, description: DESC, isPartOf: { "@id": SITE + "/#website" }, about: { "@id": SITE + "/#app" }, mainEntity: { "@id": SITE + "/#app" }, primaryImageOfPage: { "@type": "ImageObject", contentUrl: SITE + "/og.png", width: 1200, height: 630 }, video: { "@id": SITE + "/#demo-film" }, datePublished: "2026-08-07", dateModified: LASTMOD, inLanguage: "en" },
    {
      "@type": "SoftwareApplication", "@id": SITE + "/#app", name: "fein", alternateName: "Fein",
      applicationCategory: "BusinessApplication", applicationSubCategory: "Relationship intelligence",
      operatingSystem: "Self-hosted (Docker)", description: DESC_LONG, url: SITE + "/",
      provider: { "@id": SITE + "/#org" }, isAccessibleForFree: true, featureList: FEATURES,
      license: "https://www.apache.org/licenses/LICENSE-2.0",
      installUrl: REPO_URL, downloadUrl: REPO_URL,
      softwareHelp: { "@type": "CreativeWork", url: SITE + "/self-host" },
      softwareRequirements: "Docker, self-hosted on the team's own infrastructure",
      offers: OFFERS_ALL,
      keywords: "venture capital, private equity, relationship intelligence, warm introductions, deal memory, meeting preparation, LP relations, context graph, MCP endpoint, open source",
      audience: { "@type": "Audience", audienceType: ["Venture capital teams", "Private equity teams", "Fundraising and LP relations teams", "Portfolio and platform teams"] }
    }
  ]
};
const ldScript = '<script type="application/ld+json">' + JSON.stringify(ld) + "</script>";

const headMeta = `<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${TITLE}</title>
<meta name="description" content="${DESC}">
<link rel="canonical" href="${SITE}/">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
<meta name="color-scheme" content="dark">
<meta name="theme-color" content="#08090A">
<meta name="author" content="fein">
<meta name="application-name" content="fein">
<meta name="apple-mobile-web-app-title" content="fein">
<meta name="format-detection" content="telephone=no">
<link rel="icon" href="/favicon.ico" sizes="48x48 32x32 16x16">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="sitemap" type="application/xml" href="/sitemap.xml">
<link rel="alternate" type="text/plain" href="/llms.txt" title="fein for AI assistants (summary)">
<link rel="alternate" type="text/plain" href="/llms-full.txt" title="fein for AI assistants (full page)">
<meta property="og:type" content="website">
<meta property="og:site_name" content="fein">
<meta property="og:locale" content="en_US">
<meta property="og:title" content="${TITLE}">
<meta property="og:description" content="${DESC_LONG}">
<meta property="og:url" content="${SITE}/">
<meta property="og:image" content="${SITE}/og.png">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="fein · the memory layer for venture capital">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${TITLE}">
<meta name="twitter:description" content="${DESC}">
<meta name="twitter:image" content="${SITE}/og.png">
<meta name="twitter:image:alt" content="fein · the memory layer for venture capital">`;

// GoatCounter retired Aug 2026: Vercel Web Analytics is the one counter now.
const analytics = `<script>window.va=window.va||function(){(window.vaq=window.vaq||[]).push(arguments)}</script>
<script defer src="/_vercel/insights/script.js"></script>
<script defer src="/_vercel/speed-insights/script.js"></script>`;
// The /_vercel/* pair is Vercel Web Analytics + Speed Insights, first-party
// routes that only resolve on the Vercel deployment (both toggled on for
// fein-site); anywhere else they 404 quietly. Also in 404.html by hand.

// PostHog product analytics — standalone site only, never the artifact (same CSP
// reason as GoatCounter). INERT by default: paste a project API key (phc_...) into
// POSTHOG_KEY to enable, an empty string emits nothing and index.html is unchanged.
// Complements GoatCounter + Vercel with funnels and session insight on the
// #get-started flow. NOTE: confirm the tool with Daniel ("postdoc" was dictated)
// and pick the region host before enabling. Official array.js loader.
const POSTHOG_KEY = ""; // e.g. "phc_..." — leave empty to keep PostHog disabled
const POSTHOG_HOST = "https://us.i.posthog.com"; // EU: https://eu.i.posthog.com
const posthog = POSTHOG_KEY ? `
<script>!function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.crossOrigin="anonymous",p.async=!0,p.src=s.api_host.replace(".i.posthog.com","-assets.i.posthog.com")+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="init capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug getPageViewId captureTraceFeedback captureTraceMetric".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);posthog.init("${POSTHOG_KEY}",{api_host:"${POSTHOG_HOST}",person_profiles:"identified_only",capture_pageview:true})</script>` : "";

// "Send us a message" widget — self-hosted, replacing Intercom (which cost a
// subscription and, measured on the live page, 10 requests / 908 KB / up to
// 570 ms of main-thread work per engaged visitor). Same white pill with
// Daniel's face (avatars/daniel.webp, inlined so the page stays one file);
// clicking it now opens a small on-page card whose form POSTs to
// /api/message, which mails NOTIFY_TO via Resend with reply_to set to the
// visitor. The reply is Daniel answering from his inbox: no third party, no
// widget boot, nothing on the load path. The nav's "Send a message" link
// (#nav-chat, see the tpl) opens the same card; its mailto href is the
// no-JS fallback. The honeypot input (`website`) and the ms-between-open-
// and-submit field (`t`) mirror /api/enquiry's guards. The whole block is
// wrapped in <!--fein-chat--> markers so rederive-tpl.js can strip it back
// out cleanly. The block lands on pages that define none of the site tokens
// (/privacy, /terms, 404), where a bare var() would drop the whole
// declaration: so every var() here carries its literal fallback, the same
// rule the nav slice follows.
const danielB64 = fs.readFileSync("avatars/daniel.webp").toString("base64");
const chat = `
<!--fein-chat:start-->
<style>
#fein-chat{--fc-disc:#fff;position:fixed;right:20px;bottom:20px;z-index:2147483000;display:inline-flex;align-items:center;gap:10px;margin:0;padding:8px 16px 8px 8px;font-family:var(--font,'Inter','Inter Fallback',system-ui,sans-serif);background:var(--fc-disc);border:0;border-radius:999px;cursor:pointer;box-shadow:0 2px 8px rgba(0,0,0,.5),0 16px 40px -12px rgba(0,0,0,.85);opacity:0;transform:translateY(6px);transition:opacity .3s ease,transform .3s cubic-bezier(.22,.61,.36,1),box-shadow .2s ease;-webkit-tap-highlight-color:transparent}
#fein-chat.fc-in{opacity:1;transform:none}
#fein-chat:hover{transform:translateY(-1px);box-shadow:0 2px 8px rgba(0,0,0,.5),0 22px 52px -12px rgba(0,0,0,.9)}
#fein-chat:focus-visible{outline:2px solid var(--blue-l,#52A8FF);outline-offset:2px}
#fein-chat .fc-mark{position:relative;flex:none;width:38px;height:38px}
#fein-chat .fc-mark img{display:block;width:100%;height:100%;border-radius:50%;object-fit:cover}
#fein-chat .fc-txt{display:flex;flex-direction:column;align-items:flex-start;gap:1px;line-height:1.2;text-align:left}
#fein-chat .fc-txt b{font-weight:600;font-size:13px;letter-spacing:-.01em;color:#0b0c0e}
#fein-chat.fc-open{opacity:0;transform:translateY(6px);pointer-events:none}
@media(max-width:520px){#fein-chat{padding:0;width:54px;height:54px;gap:0;justify-content:center}#fein-chat .fc-txt{display:none}#fein-chat .fc-mark{width:54px;height:54px}}
@media(prefers-reduced-motion:reduce){#fein-chat,#fein-chat.fc-in{transition:opacity .2s ease;transform:none}#fein-chat:hover{transform:none}}
#fein-msg{position:fixed;right:20px;bottom:20px;z-index:2147483001;width:min(360px,calc(100vw - 32px));font-family:var(--font,'Inter','Inter Fallback',system-ui,sans-serif);background:#fff;color:#0b0c0e;border-radius:16px;box-shadow:0 2px 8px rgba(0,0,0,.5),0 24px 64px -16px rgba(0,0,0,.9);overflow:hidden}
#fein-msg .fm-head{display:flex;align-items:center;gap:10px;padding:14px 14px 12px;border-bottom:1px solid #ececef}
#fein-msg .fm-head img{flex:none;width:34px;height:34px;border-radius:50%;object-fit:cover}
#fein-msg .fm-who{display:flex;flex-direction:column;gap:1px;line-height:1.25;min-width:0}
#fein-msg .fm-who b{font-weight:600;font-size:13.5px;letter-spacing:-.01em}
#fein-msg .fm-who span{font-size:12px;color:#6f7076}
#fein-msg #fm-close{margin-left:auto;flex:none;display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;padding:0;border:0;border-radius:8px;background:transparent;color:#6f7076;cursor:pointer}
#fein-msg #fm-close:hover{background:#f2f2f4;color:#0b0c0e}
#fein-msg form{display:flex;flex-direction:column;gap:8px;padding:12px 14px 14px}
#fein-msg #fm-hp{position:absolute;left:-9999px;width:1px;height:1px;opacity:0}
#fein-msg input[type=email],#fein-msg textarea{width:100%;box-sizing:border-box;padding:9px 11px;font:inherit;font-size:14px;color:#0b0c0e;background:#fff;border:1px solid #d9d9de;border-radius:10px;outline:none}
#fein-msg input[type=email]:focus,#fein-msg textarea:focus{border-color:var(--blue-l,#52A8FF);box-shadow:0 0 0 3px rgba(82,168,255,.18)}
#fein-msg textarea{resize:vertical;min-height:88px}
#fein-msg .fm-err{margin:0;font-size:12.5px;line-height:1.4;color:#c62f21}
#fein-msg .fm-err a{color:inherit}
#fein-msg #fm-send{align-self:flex-end;padding:8px 18px;font:inherit;font-size:13.5px;font-weight:600;color:#fff;background:#0b0c0e;border:0;border-radius:999px;cursor:pointer}
#fein-msg #fm-send:hover{background:#26272b}
#fein-msg #fm-send:disabled{opacity:.6;cursor:default}
#fein-msg #fm-done{padding:20px 16px 22px;text-align:center}
#fein-msg #fm-done b{display:block;font-size:14.5px;font-weight:600}
#fein-msg #fm-done p{margin:6px 0 0;font-size:13px;line-height:1.5;color:#6f7076}
@media(max-width:520px){#fein-msg{right:16px;bottom:16px}}
</style>
<button type="button" id="fein-chat" aria-label="Send the fein team a message.">
<span class="fc-mark"><img src="data:image/webp;base64,${danielB64}" alt="" width="38" height="38"></span>
<span class="fc-txt"><b>Send us a message</b></span>
</button>
<div id="fein-msg" role="dialog" aria-label="Send us a message" hidden>
<div class="fm-head">
<img src="data:image/webp;base64,${danielB64}" alt="" width="34" height="34">
<div class="fm-who"><b>Send us a message</b><span>You're writing to the founder. Replies usually same day.</span></div>
<button type="button" id="fm-close" aria-label="Close"><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true"><path d="M6 6L18 18"/><path d="M18 6L6 18"/></svg></button>
</div>
<div id="fm-body">
<form id="fm-form" novalidate>
<input id="fm-hp" name="website" type="text" tabindex="-1" autocomplete="off" aria-hidden="true">
<input id="fm-email" name="email" type="email" placeholder="you@fund.com" autocomplete="email" required aria-label="Your email">
<textarea id="fm-text" name="message" rows="4" placeholder="Ask anything. Pricing, setup, whether it works with your CRM&#8230;" required aria-label="Your message"></textarea>
<p id="fm-err" class="fm-err" hidden></p>
<button type="submit" id="fm-send">Send</button>
</form>
</div>
<div id="fm-done" hidden><b>Sent.</b><p>Daniel replies to your inbox, usually the same day.</p></div>
</div>
<script>(function(){var d=document,w=window;
var pill=d.getElementById("fein-chat"),panel=d.getElementById("fein-msg");
if(!pill||!panel)return;
requestAnimationFrame(function(){requestAnimationFrame(function(){pill.classList.add("fc-in")})});
var openedAt=0;
function openPanel(){panel.hidden=false;pill.classList.add("fc-open");openedAt=Date.now();var e=d.getElementById("fm-email");if(e)setTimeout(function(){e.focus()},60)}
function closePanel(){panel.hidden=true;pill.classList.remove("fc-open");pill.focus()}
pill.addEventListener("click",openPanel);
var x=d.getElementById("fm-close");if(x)x.addEventListener("click",closePanel);
var n=d.getElementById("nav-chat");if(n)n.addEventListener("click",function(e){e.preventDefault();openPanel()});
d.addEventListener("keydown",function(e){if(e.key==="Escape"&&!panel.hidden)closePanel()});
if(location.hash==="#chat")openPanel();
var form=d.getElementById("fm-form"),btn=d.getElementById("fm-send"),err=d.getElementById("fm-err");
form.addEventListener("submit",function(e){e.preventDefault();
var email=d.getElementById("fm-email").value.trim(),msg=d.getElementById("fm-text").value.trim();
if(!email||email.indexOf("@")<1){err.textContent="Enter your email so the reply can reach you.";err.hidden=false;return}
if(!msg){err.textContent="Write a message first.";err.hidden=false;return}
err.hidden=true;btn.disabled=true;btn.textContent="Sending…";
fetch("/api/message",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:email,message:msg,website:d.getElementById("fm-hp").value,t:Date.now()-openedAt,page:location.pathname})})
.then(function(r){if(!r.ok)throw 0;return r.json()})
.then(function(){d.getElementById("fm-body").hidden=true;d.getElementById("fm-done").hidden=false})
.catch(function(){btn.disabled=false;btn.textContent="Send";err.innerHTML='Something broke. Email us instead: <a href="mailto:sales@fein.vc">sales@fein.vc</a>';err.hidden=false})})})()</script>
<!--fein-chat:end-->`;

// ---- "Get a demo" modal — site-wide, wrapped in <!--fein-demo--> markers so
// rederive-tpl.js can strip it back out cleanly. Lives in src/demo-modal.html
// (markers included). Every a[href="/demo"] opens it: step one asks only for
// the email, step two the demo page's other questions, then the cal.com
// booking modal opens over the page with everything prefilled. The /demo page
// keeps working unchanged: it is the no-JS fallback, the direct-URL landing,
// and the one page the modal script deliberately no-ops on (so the block is
// not injected there either; nothing on that page would use it).
const demoModal = fs.readFileSync("demo-modal.html", "utf8");
if (demoModal.indexOf("<!--fein-demo:start-->") < 0 || demoModal.indexOf("<!--fein-demo:end-->") < 0)
  throw new Error("demo-modal.html: fein-demo markers missing");

// ---- distill: the served home page cuts the sections that restate one
// another. #change and #proof restate what the #memory thread and /security
// already show, #why answers an objection the sales call handles, and #crm
// repeats the works strip as a wall. This ran as the /b variant first and
// won; the template keeps all thirteen sections as the source of truth, so
// any of them comes back by removing its id here. #figures came back as the
// three use-case cards: sourcing, raising, portfolio. ----
const HOME_CUT = ["change", "proof", "why", "crm", "how"];
let homeRest = rest;
HOME_CUT.forEach(function (id) {
  const re = new RegExp('\\n?<section id="' + id + '"[\\s\\S]*?</section>');
  if (!re.test(homeRest)) throw new Error("home: section to cut not found: #" + id);
  homeRest = homeRest.replace(re, "");
});
["change", "proof", "why", "crm"].forEach(function (id) {
  if (homeRest.indexOf('href="#' + id + '"') > -1) throw new Error("home: link into cut section #" + id + " — repoint it in the template");
});
// #change is cut above, so its replay script would open with a guaranteed-null
// querySelector on every home load: dead bytes on the page most people see.
// Strip the marked block, markers included, from the home output only. The
// copy /security receives is sliced from `rest` further down, so the template's
// block still lands where the section actually renders.
if (homeRest.indexOf("/*change-replay:start*/") < 0) throw new Error("home: change-replay markers not found to strip");
homeRest = homeRest.replace(/\n?\/\*change-replay:start\*\/[\s\S]*?\/\*change-replay:end\*\//, "");

const indexHtml = `<!doctype html>
<html lang="en">
<head>
${headMeta}
${styleBlock}
${ldScript}
</head>
<body>
${homeRest}
${spriteRest}
${analytics}${posthog}${chat}${demoModal}
</body>
</html>`;

// ---- write site ----
const out = "..";
fs.mkdirSync(out, { recursive: true });
assertCharsetCovers(indexHtml, "index.html");
fs.writeFileSync(path.join(out, "index.html"), indexHtml);

// ---- /b: the distilled page previewed here before it became the home page.
// Kept as an alias so the review URL keeps working: same document, canonical
// already points at the root, noindex so search engines never see two copies.
const bHtml = indexHtml.replace(/<meta name="robots" content="[^"]*">/, '<meta name="robots" content="noindex, follow">');
fs.mkdirSync(path.join(out, "b"), { recursive: true });
fs.writeFileSync(path.join(out, "b", "index.html"), bHtml);

// ---- 404: generated from src/404.html like every other page, rather than
// hand-maintained at the repo root. The page keeps its own small standalone
// sheet, so the build's only jobs are the fonts and the chat launcher: inline
// the two subset faces, strip any fein-chat block already in the source (the
// markers make this idempotent), and append the current one before writing.
// No head prefetch hints: an error page does not need the warm-up. ----
let notFound = fs.readFileSync("404.html", "utf8");
if (notFound.indexOf("__GEIST_SANS_B64__") < 0 || notFound.indexOf("__INTER_B64__") < 0)
  throw new Error("404.html: font placeholders missing in src/404.html (it must carry __GEIST_SANS_B64__ and __INTER_B64__)");
notFound = notFound
  .split("__GEIST_SANS_B64__").join(sansB64)
  .split("__INTER_B64__").join(interB64)
  .replace(/\s*<!--fein-chat:start-->[\s\S]*?<!--fein-chat:end-->/g, "")
  .replace(/\s*<!--fein-demo:start-->[\s\S]*?<!--fein-demo:end-->/g, "");
if (notFound.indexOf("__GEIST") > -1 || notFound.indexOf("__INTER") > -1) throw new Error("font placeholder left in 404");
if (chat) {
  if (notFound.indexOf("</body>") < 0) throw new Error("404.html: no </body> to patch the chat launcher into");
  // the 404 page's one call to action is its "Get a demo" link, so the modal
  // rides along here too
  notFound = notFound.replace("</body>", chat + demoModal + "\n</body>");
}
assertCharsetCovers(notFound, "404.html");
fs.writeFileSync(path.join(out, "404.html"), notFound);

// robots.txt — welcome AI answer engines explicitly
const aiBots = ["GPTBot", "OAI-SearchBot", "ChatGPT-User", "ClaudeBot", "Claude-User", "Claude-SearchBot", "Claude-Web", "anthropic-ai", "PerplexityBot", "Perplexity-User", "Google-Extended", "Google-CloudVertexBot", "Google-NotebookLM", "GoogleAgent-Mariner", "GoogleOther", "Applebot", "Applebot-Extended", "Bingbot", "Bytespider", "CCBot", "Amazonbot", "Meta-ExternalAgent", "Meta-ExternalFetcher", "cohere-ai", "cohere-training-data-crawler", "AI2Bot", "DuckAssistBot", "YouBot", "MistralAI-User", "DeepSeekBot", "Diffbot", "Timpibot", "omgilibot", "Webzio-Extended", "kagi-fetcher"];
const robots = `# fein · the memory layer for venture capital
# AI assistants welcome. Summary: ${SITE}/llms.txt · Full page: ${SITE}/llms-full.txt

User-agent: *
Allow: /

${aiBots.map(b => `User-agent: ${b}\nAllow: /`).join("\n\n")}

Sitemap: ${SITE}/sitemap.xml
`;
fs.writeFileSync(path.join(out, "robots.txt"), robots);

// sitemap.xml
fs.writeFileSync(path.join(out, "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
  <url><loc>${SITE}/</loc><lastmod>${LASTMOD}</lastmod><changefreq>weekly</changefreq><priority>1.0</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image><video:video><video:thumbnail_loc>${SITE}/video/fein-demo-poster.jpg</video:thumbnail_loc><video:title>${VIDEO_NAME}</video:title><video:description>${VIDEO_DESC}</video:description><video:content_loc>${SITE}/video/fein-demo-1440.mp4</video:content_loc><video:duration>26</video:duration><video:publication_date>${VIDEO_UPLOADED}</video:publication_date><video:family_friendly>yes</video:family_friendly><video:live>no</video:live></video:video></url>
  <url><loc>${SITE}/pricing</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.9</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image></url>
  <url><loc>${SITE}/deploy</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.9</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image></url>
  <url><loc>${SITE}/self-host</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image></url>
  <url><loc>${SITE}/pe</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image></url>
  <url><loc>${SITE}/fundraising</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image></url>
  <url><loc>${SITE}/portfolio</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image></url>
  <url><loc>${SITE}/security</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image></url>
  <url><loc>${SITE}/integrations</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.7</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image></url>
  <url><loc>${SITE}/demo</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.9</priority></url>
  <url><loc>${SITE}/privacy</loc><lastmod>${LASTMOD}</lastmod><changefreq>yearly</changefreq><priority>0.3</priority></url>
  <url><loc>${SITE}/terms</loc><lastmod>${LASTMOD}</lastmod><changefreq>yearly</changefreq><priority>0.3</priority></url>
</urlset>
`);

// ---- per-page JSON-LD, same doctrine as faqLdFor below: derived from the
// page's own head (title, description, canonical, og:title), so the
// structured data can never disagree with what the page says. Every
// sub-page carries a WebPage + BreadcrumbList plus compact Organization /
// WebSite / SoftwareApplication nodes, because an answer engine reads each
// page alone and an @id pointing at a node that only exists on the home
// page resolves to nothing. The three commercial pages carry the offer
// catalogue their visible copy states. ----
const ORG_LITE = { "@type": "Organization", "@id": SITE + "/#org", name: "fein", url: SITE + "/", logo: SITE + "/icon-512.png", email: "sales@fein.vc", sameAs: [REPO_URL] };
const WEBSITE_LITE = { "@type": "WebSite", "@id": SITE + "/#website", url: SITE + "/", name: "fein", description: DESC, inLanguage: "en", publisher: { "@id": SITE + "/#org" } };
const APP_LITE = { "@type": "SoftwareApplication", "@id": SITE + "/#app", name: "fein", url: SITE + "/", applicationCategory: "BusinessApplication", operatingSystem: "Self-hosted (Docker)", description: DESC, provider: { "@id": SITE + "/#org" }, isAccessibleForFree: true, license: "https://www.apache.org/licenses/LICENSE-2.0", installUrl: REPO_URL };
const OFFERS_BY_PAGE = { pricing: OFFERS_ALL, deploy: [OFFER_MANAGED].concat(OFFERS_MONTHLY), "self-host": [OFFER_SELF_HOST] };
function headBit(page, re, label, slug) {
  const m = page.match(re);
  if (!m) throw new Error("page ld: " + label + " not found in " + slug);
  return decodeEntities(m[1].replace(/\s+/g, " ").trim());
}
function pageLdFor(page, slug) {
  const canonical = headBit(page, /<link rel="canonical" href="([^"]+)">/, "canonical", slug);
  const title = headBit(page, /<title>([\s\S]*?)<\/title>/, "title", slug);
  const desc = headBit(page, /<meta name="description" content="([^"]+)">/, "description", slug);
  // og:title is each page's short name; the legal pages suffix it with the
  // site name, which a breadcrumb does not repeat.
  const short = headBit(page, /<meta property="og:title" content="([^"]+)">/, "og:title", slug).replace(/ · fein$/, "");
  const app = OFFERS_BY_PAGE[slug] ? Object.assign({}, APP_LITE, { offers: OFFERS_BY_PAGE[slug] }) : APP_LITE;
  const ld = {
    "@context": "https://schema.org",
    "@graph": [
      ORG_LITE, WEBSITE_LITE, app,
      {
        "@type": slug === "demo" ? ["WebPage", "ContactPage"] : "WebPage",
        "@id": canonical + "#webpage", url: canonical, name: title, description: desc,
        isPartOf: { "@id": SITE + "/#website" }, about: { "@id": SITE + "/#app" },
        dateModified: LASTMOD, inLanguage: "en",
        primaryImageOfPage: { "@type": "ImageObject", contentUrl: SITE + "/og.png", width: 1200, height: 630 },
        breadcrumb: { "@id": canonical + "#breadcrumb" }
      },
      {
        "@type": "BreadcrumbList", "@id": canonical + "#breadcrumb",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "fein", item: SITE + "/" },
          { "@type": "ListItem", position: 2, name: short, item: canonical }
        ]
      }
    ]
  };
  return '<script type="application/ld+json">' + JSON.stringify(ld) + "</script>";
}

// The head links that tell an AI crawler where the plain-text mirrors live.
// The home page states them in headMeta; every generated sub-page gets the
// same three lines here.
const AI_HEAD_LINKS = `<link rel="sitemap" type="application/xml" href="/sitemap.xml">
<link rel="alternate" type="text/plain" href="/llms.txt" title="fein for AI assistants (summary)">
<link rel="alternate" type="text/plain" href="/llms-full.txt" title="fein for AI assistants (full page)">`;

// ---- legal pages (privacy, terms): standalone docs served at /privacy and
// /terms via directory-index files. Same font inlining as the main template. ----
["privacy", "terms"].forEach(function (slug) {
  let page = fs.readFileSync(path.join("legal", slug + ".html"), "utf8")
    .split("__GEIST_SANS_B64__").join(sansB64)
    .split("__INTER_B64__").join(interB64)
    // the longer token first, so __LASTMOD__ can never eat its prefix and
    // leave a stray "_HUMAN__" in the copy
    .split("__LASTMOD_HUMAN__").join(LASTMOD_HUMAN)
    .split("__LASTMOD__").join(LASTMOD)
    .split("__NAV_CSS__").join(NAV_STYLE_TAG)
    .split("__NAV__").join(navFor(slug));
  if (page.indexOf("__GEIST") > -1 || page.indexOf("__INTER") > -1 || page.indexOf("__LASTMOD") > -1 || page.indexOf("__NAV") > -1) throw new Error("legal placeholder left in " + slug);
  page = page.replace("</head>", AI_HEAD_LINKS + "\n" + pageLdFor(page, slug) + "\n</head>");
  page = page.replace("</body>", chat + demoModal + "\n</body>");
  fs.mkdirSync(path.join(out, slug), { recursive: true });
  assertCharsetCovers(page, slug + "/index.html");
  fs.writeFileSync(path.join(out, slug, "index.html"), page);
});

// ---- segment landing pages: standalone marketing docs served at /<slug> via a
// directory-index file, the same shape as the legal pages. These are the pages
// cold outbound points at, so unlike /privacy and /terms they carry the
// analytics block: the whole point is knowing which sends convert. Their form
// posts to the same /api/enquiry endpoint the modal on the index page uses.
//
// A segment page may ask for __STYLE__ and __LOGO_SPRITE__ instead of carrying
// its own copy of the design. __STYLE__ is the index page's entire <style>
// block, byte for byte, so /pe inherits the tokens, the type scale and every
// component class the home page defines -- and keeps inheriting them when the
// home page changes. That is the whole point: the alternative is a second
// stylesheet that agrees with the first only on the day it is written.
// /demo predates this and still carries its own reduced sheet, which is correct
// for a page whose job is one form; the split is per page, not global. ----
const spriteAll = spriteHero + spriteRest;

// FAQPage JSON-LD, derived from the page's own visible .faq markup so the
// structured data can never disagree with what a visitor reads. The index page
// deliberately has none (its FAQ lives only in llms.txt and is not visible
// there); these sub-pages render theirs in <details> blocks, which is exactly
// the visible-answer requirement FAQPage carries. Extraction is per <details>:
// the <summary> is the question, everything after it is the answer with tags
// stripped and entities decoded. If a page has no .faq block this returns "".
function decodeEntities(s) {
  return s
    .replace(/&rsquo;/g, "’").replace(/&lsquo;/g, "‘")
    .replace(/&rdquo;/g, "”").replace(/&ldquo;/g, "“")
    .replace(/&middot;/g, "·").replace(/&rarr;/g, "→")
    .replace(/&ndash;/g, "–").replace(/&mdash;/g, "—")
    .replace(/&hellip;/g, "…").replace(/&copy;/g, "©")
    .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(+d));
}
function faqLdFor(page, slug) {
  const m = page.match(/<div class="faq">([\s\S]*?)<\/div>/);
  if (!m) return "";
  const qa = Array.from(m[1].matchAll(/<details>\s*<summary>([\s\S]*?)<\/summary>([\s\S]*?)<\/details>/g))
    .map(d => ({
      q: decodeEntities(d[1].replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim()),
      a: decodeEntities(d[2].replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim())
    }))
    .filter(x => x.q && x.a);
  if (!qa.length) return "";
  const ld = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "@id": SITE + "/" + slug + "#faq",
    mainEntity: qa.map(x => ({
      "@type": "Question", name: x.q,
      acceptedAnswer: { "@type": "Answer", text: x.a }
    }))
  };
  return '<script type="application/ld+json">' + JSON.stringify(ld) + "</script>";
}

// /self-host, /deploy and /pricing are the fork: the free path, the managed one,
// and the page that prices them against each other. They carry no stylesheet of
// their own at all, which is what __STYLE__ was built for.
// ---- rehomed home-page sections: the sections HOME_CUT removes from the
// served home page still render, each on the page that argues it in full.
// Extracted from the built body (fonts, sprite refs and avatars already
// inlined), so a template edit to any of them lands on its new page too.
// #crm and #why make /integrations; #change joins /security with the replay
// script that animates it, lifted from between its change-replay markers.
function homeSection(id) {
  const m = rest.match(new RegExp('<section id="' + id + '"[\\s\\S]*?</section>'));
  if (!m) throw new Error("rehome: section not found in template: #" + id);
  return m[0];
}
const CHANGE_JS = sliceBetween(rest, "/*change-replay:start*/", "/*change-replay:end*/", "change-replay");

["pe", "fundraising", "portfolio", "demo", "self-host", "deploy", "pricing", "security", "integrations"].forEach(function (slug) {
  let page = fs.readFileSync(path.join("pages", slug + ".html"), "utf8")
    .split("__STYLE__").join(styleBlock)
    .split("__LOGO_SPRITE__").join(spriteAll)
    .split("__GEIST_SANS_B64__").join(sansB64)
    .split("__INTER_B64__").join(interB64)
    .split("__LASTMOD__").join(LASTMOD)
    .split("__ANALYTICS__").join(analytics)
    .split("__NAV_CSS__").join(NAV_STYLE_TAG)
    .split("__NAV__").join(navFor(slug))
    .split("__SECTION_CRM__").join(homeSection("crm"))
    .split("__SECTION_WHY__").join(homeSection("why"))
    .split("__SECTION_CHANGE__").join(homeSection("change"))
    .split("__CHANGE_JS__").join(CHANGE_JS);
  if (page.indexOf("__GEIST") > -1 || page.indexOf("__INTER") > -1 || page.indexOf("__ANALYTICS__") > -1) throw new Error("page placeholder left in " + slug);
  if (page.indexOf("__STYLE__") > -1 || page.indexOf("__LOGO_SPRITE__") > -1 || page.indexOf("__NAV") > -1) throw new Error("page placeholder left in " + slug);
  if (page.indexOf("__SECTION") > -1 || page.indexOf("__CHANGE_JS__") > -1) throw new Error("page placeholder left in " + slug);
  const faqLd = faqLdFor(page, slug);
  page = page.replace("</head>", AI_HEAD_LINKS + "\n" + pageLdFor(page, slug) + (faqLd ? "\n" + faqLd : "") + "\n</head>");
  // /demo carries this flow as a full page; the modal script no-ops there, so
  // the block would be dead bytes on the one page whose job is the same form.
  page = page.replace("</body>", chat + (slug === "demo" ? "" : demoModal) + "\n</body>");
  fs.mkdirSync(path.join(out, slug), { recursive: true });
  assertCharsetCovers(page, slug + "/index.html");
  fs.writeFileSync(path.join(out, slug, "index.html"), page);
});

// llms.txt — structured summary for AI crawlers (llms-full.txt carries the whole page)
const LLMS_SUMMARY = `> fein is the memory layer for an investment team. It is an open-source context graph that the whole team can query. It serves venture capital teams and private equity teams. It reads the team's email, calendar, notes, and CRM. It builds one context graph of every relationship the team has. The context graph shows who knows whom, and how strongly. fein scores this from real signals, not a guess. It serves the context graph to AI tools like Claude, ChatGPT, and Cursor over one MCP endpoint. Each answer arrives with its source document attached: warm introductions, meeting preparation, deal history, and the reason the team passed. AI tools traverse a deterministic map. They do not scrape documents and guess. fein is self-hosted on the team's own infrastructure. It is open source under Apache 2.0. There are two ways to have fein, and they are the same software. A team can clone the repository and run it themselves for nothing, forever: there is no paid tier of the software and no feature held back to make one. Or fein can be deployed for them by a forward deployed engineer, who connects every source, resolves duplicate people, reads the full history back, and hands over a working graph on day 14. That managed setup costs $5,000 once, then a monthly plan set by how much we keep doing, from $250 each month. There is no per-seat pricing. The paid offer is setup and upkeep, never access.`;
fs.writeFileSync(path.join(out, "llms.txt"), `# fein

${LLMS_SUMMARY}

Updated: ${LASTMOD}. Full page content in Markdown: ${SITE}/llms-full.txt

## What fein does
- Find the warmest introduction to a founder, an LP, or an operator. See who should make it.
- Prepare for meetings. See who is in the room, how you know them, and what you last discussed.
- Recall every company the team saw, and the exact reason it passed.
- Flag relationships that go cold, by each contact's own cadence.

## How it works
- fein reads your existing systems: email, calendar, Google Drive, LinkedIn, and CRMs like Attio and Affinity. It builds the context graph automatically. You keep no CRM up to date by hand.
- It serves answers over one MCP endpoint. You query it from Claude, ChatGPT, Gemini, Cursor, or any MCP client.
- We deploy it into your stack. It is live in 14 days. Your team joins two short calls.

## Your CRM stays
- fein works with 30+ tools. It reads the CRM and everything around it, then resolves the whole picture into one graph.
- It replaces no system, migrates no data, and asks the team for no new data entry. If the CRM is out of date, fein is still current, because it reads the record the team makes anyway.
- CRM and deal systems: DealCloud, Affinity, Salesforce, Attio, HubSpot, Airtable.
- Email and calendar: Gmail, Google Calendar, Outlook, Microsoft 365.
- Files and data rooms: Google Drive, SharePoint, OneDrive, Dropbox, Box, DocSend.
- Meetings, notes and chat: Granola, Zoom, Google Meet, Slack, Microsoft Teams, Notion.
- People and market data: LinkedIn, PitchBook, Crunchbase, Harmonic.
- Portfolio and back office: Carta, Standard Metrics, Google Sheets, Excel.

## For private equity
- fein serves private equity firms as well as venture capital firms. The page for private equity is ${SITE}/pe.
- An intermediary is a banker, a broker, an accountant, or a lawyer who brings a firm deals. A private equity firm has thousands of them. Their record sits in the firm's email.
- fein lists every intermediary who sends the firm deals. It scores each relationship from real signal. It names the person at the firm who owns each relationship. It flags the relationships that go quiet.
- It shows which intermediary sent each deal, what the team said, and the exact reason the firm passed, with the source document for each line.
- It works with DealCloud, Affinity, Salesforce, and Attio. It replaces no system and migrates no data.

## For fundraising
- fein serves the fundraising and LP relations side of a firm as well as the deal side. The page for fundraising is ${SITE}/fundraising.
- fein lists every LP the firm has ever spoken to, scored from real signal, with the partner who owns each relationship named.
- It flags each LP relationship that drifts away from its own rhythm, years before the raise makes it urgent.
- It files every LP ask and every commitment to the LP it belongs to, with the meeting or email it came from, and keeps it open until it is closed.
- It finds the warm path to an allocator the firm has never met, through existing LPs, founders, and co-investors.

## For portfolio teams
- fein serves the platform and portfolio support side of a firm. The page for portfolio teams is ${SITE}/portfolio.
- Before each board meeting, fein lists what is open: the asks the founder made, the promises the firm made, and what changed since the last pack.
- It files every promised introduction to the company it belongs to, marks the ones that happened, and flags the ones still open.
- It matches a founder's ask for a hire, a customer, or an expert against the firm's whole graph, ranked by how warm each path is.
- It keeps the record of what the firm did for each company, with a source behind every line.

## Pricing
- There are two ways to have fein and they run the same software. The full comparison is at ${SITE}/pricing.
- Running it yourself is free, forever. The code is Apache 2.0 licensed. There is no paid tier of the software, and no feature is held back to make one. The page for this path is ${SITE}/self-host.
- The paid offer is setup and upkeep, never access. The page for this path is ${SITE}/deploy.
- Managed setup: $5,000 to build once. A forward deployed engineer connects every source, resolves duplicate people, reads the firm's full history back, and hands over a working graph on day 14.
- Then a monthly plan, set by how much we keep doing after the setup, never per seat: Core is $250 each month, Plus is $500, Pro is $750.
- Core keeps the connectors working through upstream API changes and applies updates. Plus adds new answers on request and a quarterly graph review. Pro adds new connectors for new tools and a named engineer.
- An annual plan, paid in advance, costs 15% less.
- It is month to month, with no lock-in. If you cancel, the software and the graph stay yours and keep running. What stops is the upkeep.

## Security and data
- The security page is ${SITE}/security.
- It is self-hosted in the team's own environment. Data never leaves it. There is no telemetry and no control plane.
- It is open source and auditable from end to end. A team can clone the repo and run fein. The paid offer is setup and upkeep.
- One token gates the dashboard, the API, and the agent endpoint.
- Access is per person. Each person's sensitive sources live in a private layer, and fein enforces the scoping inside every query.
- Every ingest, merge, and review decision is written to an append only audit trail, with the person or agent that made it.

## FAQ

${faqs.map(([q, a]) => `### ${q}\n${a}`).join("\n\n")}

## Contact
- [Get a demo](${SITE}/demo): talk to sales about a 14 day build
- [Email sales](mailto:sales@fein.vc): sales@fein.vc

## Links
- [Run fein yourself](${SITE}/self-host): the free path. What the setup involves, what it needs, and how long each part really takes
- [Managed setup](${SITE}/deploy): the paid path. A forward deployed engineer builds fein into the firm's stack in 14 days
- [Pricing](${SITE}/pricing): both paths priced against each other, with the three monthly plans
- [fein for private equity](${SITE}/pe): the page for private equity firms
- [fein for fundraising](${SITE}/fundraising): the page for LP relations and the next raise
- [fein for portfolio teams](${SITE}/portfolio): the page for platform and portfolio support
- [Security](${SITE}/security): self-hosted, open source, auditable. The page for a security review
- [Integrations](${SITE}/integrations): the 30+ tools fein reads, and the assistants it answers in
- [Source on GitHub](https://github.com/clippycommits/fein): Apache 2.0 licensed, free to self-host
- [Full page content for LLMs](${SITE}/llms-full.txt): the whole page in Markdown
- [Sitemap](${SITE}/sitemap.xml): every indexable URL
`);

// llms-full.txt — the whole page, mirrored in Markdown for AI answer engines.
// Every line here restates visible site copy; keep it in sync when copy changes.
fs.writeFileSync(path.join(out, "llms-full.txt"), `# fein · the memory layer for venture capital

${LLMS_SUMMARY}

Updated: ${LASTMOD}. This file mirrors the full content of ${SITE}/ for AI assistants and answer engines. Summary version: ${SITE}/llms.txt

## What fein is

fein reads your team's email, calendar, notes, and CRM. It builds one context graph of every relationship your team has. It answers in Claude, ChatGPT, and Cursor. Each answer carries its source document. Self-hosted, open source, live in 14 days.

You add no new CRM. Your team logs nothing. The context graph builds itself from the record your team already makes.

It reads and answers in the tools you already use: Gmail, Google Calendar, Drive, Attio, LinkedIn, Granola, Notion, Slack, Claude, ChatGPT, Gemini, Cursor, Perplexity, and Copilot.

## The film: fein in twenty-six seconds

There is a twenty-six second narrated walkthrough on the page, at ${SITE}/#memory (video: ${SITE}/video/fein-demo-1440.mp4). Its narration, verbatim:

"Introducing fein. Privacy-first, open-source, agentic memory layer, purpose-built for venture capital. Humans and agents can speak with fein to query and understand facts over time. Team members draw from the same system of record: a single endpoint for all of your AI agents to query and understand your VC's knowledge base."

What it shows: a partner asks "Who is the warmest path into Halo Compute, and what did we say when we passed?" fein reads seven documents across four sources in 1.8 seconds and answers with six citations. Dev Raman is the warmest path. The firm passed in January 2025 for two stated reasons, and three of the facts behind that decision are no longer true. The film then shows the memory behind the answer, every fact carrying the document it was read out of, and the eight systems fein reads continuously.

## What changes when a fact stops being true

fein holds one live record per company and retires facts that stop being true rather than overwriting them. A retired fact keeps the dates it was true between, so the history stays queryable: you can ask what the firm believed at the moment it made a decision, not only what is true now. Nobody opens a CRM to correct a title, and no stale row survives because the person who knew was on holiday.

## How it works: nobody enters data, the graph builds itself

fein reads the record your team already makes. It resolves that record into one live graph: who exists, who knows whom, and how well. Your AI tools read the graph. They stop guessing.

1. Reads everything your team already uses: your inbox, calendar, Drive, LinkedIn, and CRM, read continuously. Your team logs nothing.
2. Resolves it into one identity per person, not a hundred duplicates: fein resolves every copy of a contact into one identity. It scores the strength from real signals (meetings, replies, and shared documents), not an LLM guess.
3. Answers wherever your team asks: ask in Claude, ChatGPT, Gemini, or Cursor over one MCP endpoint. You get the same answer every time, with the email behind it.

## fein vs. a connector alone

A connector gives an assistant a search box into one tool at a time. fein gives it your firm's whole memory, with the source document behind every line. fein reads your tools continuously. It resolves them into one context graph. It answers over one MCP endpoint.

- How it connects. Connector alone: each tool needs its own plug-in, and your assistant queries them one at a time. With fein: the same plug. fein is one MCP endpoint. Your assistant already knows how to call it. Behind it sits the graph, not a search box.
- What it reads. Connector alone: whatever matches your query, this minute, in one tool. If your words miss the words in the email, the fact does not exist. With fein: a context graph. fein has already read every message, call and meeting. Each one is filed to its person and company before you ask.
- Across your stack. Connector alone: Gmail cannot join a call transcript to a job change to a calendar invite. Each search stands alone. You join the results yourself. With fein: one graph, not many searches. The email, the transcript and the invite land on the same record. One answer can cross all three.
- When a fact changes. Connector alone: it returns what it finds. That includes the line that stopped being true eighteen months ago. Search does not know the difference. With fein: auditable. The old fact is struck, dated and kept. You get what is true now. You can still ask what your firm believed in 2024.
- What comes back. Connector alone: a paraphrase of some documents. It is as good as whatever was retrieved that time. Ask twice, get two answers. With fein: deterministic. The same question gets the same answer, every time. The document behind each line is one click away.
- Where it runs. Connector alone: your data leaves your firm. It goes to whichever vendor owns the connector. With fein: yours. It runs on your own servers. You can read all of the code. It sends nothing to us.

## What you get: four questions your team asks every week

The warm introduction. The brief before the meeting. The reason you passed. The relationship that goes quiet. fein answers each one from your team's history, in seconds.

### Your team already has the introduction you need.
Ask for the warmest path to a founder or an LP. fein reads the real graph of who meets and emails whom. It weighs each hop. It names the best person to make the introduction. This is not only the person who knows them.

### Get a brief before each meeting.
fein shows the attendees, how you know each of them, and what was open. It gets this from your calendar and inbox. It is on your screen before the meeting starts.

### Ask one question to see why you passed.
A company can come back for its next round. Then fein shows the meeting, the memo, and the exact reason in seconds. It traces each line to its source document.

### Relationships go cold. fein sees it first.
fein learns the rhythm of each relationship from your real history. Then it flags the ones that drift away from it. It uses dates and intervals, not a guess.

## Your CRM stays: it sits on top of the systems you run today

fein works with 30+ tools. It reads your CRM and everything around it, then resolves the whole picture into one graph. It replaces no system, migrates no data, and asks your team for no new data entry. If your CRM is out of date, fein is still current, because it reads the record your team makes anyway.

- CRM and deal systems: DealCloud, Affinity, Salesforce, Attio, HubSpot, Airtable
- Email and calendar: Gmail, Google Calendar, Outlook, Microsoft 365
- Files and data rooms: Google Drive, SharePoint, OneDrive, Dropbox, Box, DocSend
- Meetings, notes and chat: Granola, Zoom, Google Meet, Slack, Microsoft Teams, Notion
- People and market data: LinkedIn, PitchBook, Crunchbase, Harmonic
- Portfolio and back office: Carta, Standard Metrics, Google Sheets, Excel
- 30+ tools in all. If your team runs something else, we read that too.

## Security: ${SITE}/security

Your data never leaves your servers. fein reads your inbox, calendar, and CRM to do its work. It does this on your own servers. You can read all of the code.

- Always self-hosted. It runs on your infrastructure. It sends nothing to us.
- Open source, end to end. Every line that touches your data is public. Read it before you run it.
- One token, every surface. The dashboard, the API, and the agent endpoint sit behind the same gate.
- Private by person. Each person's sensitive sources stay in their own layer inside the shared graph.
- Every change is written down. Ingests, merges, and decisions are logged with the person or agent that made them.
- Nothing phones home. No telemetry, no analytics, and no control plane of ours to trust.

## Managed installation: we deploy fein in two weeks

We deploy fein in two weeks. Then it works on its own. Your only part is two short calls. By day fourteen, fein holds your team's full history, and it works like it has been here for years. It drafts the brief before each meeting, and it shows the source for each answer.

- Day 1, we connect your systems: on the first call, we connect your email, calendar, Drive, LinkedIn, and CRM. This runs on your own servers.
- Days 2-13, it reads your full history: it reads years of email, meetings, and documents. It joins every copy of each person into one record. The whole team shares this record. Nobody maintains it by hand.
- Day 14, you check it, then it goes live: on a second short call, you check the answers against what you know. Then fein goes live. It holds your team's full history, like a colleague of many years.

## For private equity: ${SITE}/pe

fein serves private equity firms as well as venture capital firms. The page at ${SITE}/pe describes the same product in the language a deal team uses.

An intermediary is a banker, a broker, an accountant, or a lawyer who brings a firm deals. A private equity firm has thousands of them, and the record of those relationships sits in ten thousand emails. Four problems follow from that. Coverage is a guess, because the CRM shows one picture and the inbox shows another. Relationships go quiet in silence, and the firm learns this when the next deal goes to a competitor. Ownership leaves when a partner leaves, because what the partner knew was never written down. Deal history is not searchable, because the memo, the reason, and the intermediary sit in three systems and one person's memory.

fein answers four questions for a deal team. It lists every intermediary who sends the firm deals, scored from real signal, with the owner of each relationship named. It flags each relationship that drifts away from its own rhythm, with the last contact and the colleague who must make the call. It shows which intermediary sent each deal, what the team said, and the exact reason the firm passed, with the source document for each line. It finds the shortest real path to a management team, a seller, an operator, or an LP, and names the best colleague to make the introduction.

fein works with DealCloud, Affinity, Salesforce, and Attio. It reads the CRM and everything around it. It replaces no system, it migrates no data, and it asks the team for no new data entry.

## For fundraising: ${SITE}/fundraising

fein serves the fundraising and LP relations side of a firm as well as the deal side. The page at ${SITE}/fundraising describes the same product in the language an IR desk uses.

The next fund is raised in the two years before it opens, and the record of the firm's LP relationships sits in four partners' inboxes. Four problems follow from that. Coverage is a partner's memory, rebuilt by hand when the raise opens. Promises made to LPs quietly expire, and the LP remembers. Quiet is invisible until it is expensive, because an anchor drifts from quarterly contact to nothing and the firm learns it when the re-up conversation starts cold. The last raise is not searchable, because who passed and the stated reason sit in threads three years old.

fein answers four questions for an IR desk. It lists every LP the firm has ever spoken to, scored from real signal, with the partner who owns each relationship named. It flags each LP relationship that drifts away from its own rhythm, years before the raise makes it urgent. It files every LP ask and every commitment to the LP it belongs to, with the meeting or email it came from, and keeps it open until it is closed. It finds the warm path to an allocator the firm has never met, through existing LPs, founders, and co-investors.

## For portfolio teams: ${SITE}/portfolio

fein serves the platform and portfolio support side of a firm. The page at ${SITE}/portfolio describes the same product in the language a platform team uses.

Founders remember what the firm promised, and the firm's tools do not. Four problems follow from that. Board prep is an excavation across three tools and one partner's inbox. Promised introductions vanish, because a month after the board nobody can list them. Founder asks die in Slack, because the right candidate emailed a partner last week and the two facts never meet. The help is invisible later, because the record of what the firm did for each company is nobody's single list.

fein answers four questions for a platform team. Before each board meeting it lists what is open: the asks the founder made, the promises the firm made, and what changed since the last pack. It files every promised introduction to the company it belongs to, marks the ones that happened, and flags the ones still open. It matches a founder's ask for a hire, a customer, or an expert against the firm's whole graph, ranked by how warm each path is, ending in the colleague who should make the call. It keeps the record of what the firm did for each company, with a source behind every line.

## Pricing

Every investment team needs a data engineer. Now every team can afford one.

| Option | Price | What you get |
| --- | --- | --- |
| A data hire | $200,000 per year | Skilled, but one person. The graph stays in their head. |
| fein | $5,000 once + a monthly plan from $250 | We build it into your stack in two weeks and keep it current for you. Live in 14 days. |
| Clone it yourself | $0 forever | The same code we deploy for clients. You run it and you maintain it. |

The monthly plan is set by how much we keep doing after the setup, and never per seat.

| Plan | Monthly | What it adds |
| --- | --- | --- |
| Core | $250 | Connectors repaired after upstream API changes, updates and security patches applied, email support. |
| Plus | $500 | Everything in Core, plus new answers built on request, a quarterly graph review, priority support. |
| Pro | $750 | Everything in Plus, plus new connectors built for new tools, a named engineer, same-day support. |

The fein plan reads your inbox, calendar, Drive, LinkedIn, and CRM. It resolves entities to one identity per person. It scores every relationship from real signals, not a guess. It answers over one MCP endpoint in Claude, ChatGPT, Gemini, and Cursor. It is open source and runs on your servers. We keep the connectors working through every API change. We build new answers when your team asks.

A firm on Core pays $8,000 in the first year. That is a fraction of one month of a data hire. An annual plan, paid in advance, costs 15% less. It is month to month, open source, and self-hosted. If you cancel, everything continues to run.

## FAQ

${faqs.map(([q, a]) => `### ${q}\n${a}`).join("\n\n")}

## Contact

- [Get a demo](${SITE}/demo): the form on the site, two short calls to go live
- [Email sales](mailto:sales@fein.vc): sales@fein.vc
- [Get the repo](https://github.com/clippycommits/fein): the source on GitHub, Apache 2.0 licensed, free to self-host
`);

// favicon.svg — theme-adaptive graph mark
fs.writeFileSync(path.join(out, "favicon.svg"), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<style>line{stroke:#000;stroke-width:2.4}circle{fill:#000}@media(prefers-color-scheme:dark){line{stroke:#fff}circle{fill:#fff}}</style>
<line x1="7" y1="24" x2="22" y2="9"/><line x1="22" y1="9" x2="24.5" y2="24"/>
<circle cx="7" cy="24" r="3.6"/><circle cx="22" cy="9" r="3.6"/><circle cx="24.5" cy="24" r="2.4"/>
</svg>
`);

// web manifest
fs.writeFileSync(path.join(out, "site.webmanifest"), JSON.stringify({
  name: "fein", short_name: "fein", description: "The memory layer for venture capital.",
  start_url: "/", display: "standalone", background_color: "#08090A", theme_color: "#08090A",
  icons: [
    { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
    { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
    { src: "/icon-512-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    { src: "/favicon.svg", sizes: "any", type: "image/svg+xml" }
  ]
}, null, 2));

// GitHub Pages helpers
fs.writeFileSync(path.join(out, "CNAME"), "fein.vc\n");
fs.writeFileSync(path.join(out, ".nojekyll"), "");

// og.svg — square canvas (1200x1200) with the 1200x630 design centered vertically,
// so a centered crop recovers it undistorted (qlmanage renders square SVGs 1:1).
fs.writeFileSync("og.svg", `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1200" viewBox="0 0 1200 1200">
<defs><style>
@font-face{font-family:'Geist';font-weight:400 600;src:url(data:font/woff2;base64,${sansB64}) format('woff2');}
text{font-family:'Geist','Helvetica Neue',Arial,sans-serif}
</style></defs>
<rect width="1200" height="1200" fill="#000000"/>
<g transform="translate(0,285)">
<g stroke="#2b2b2b" stroke-width="2" fill="#2b2b2b">
<line x1="960" y1="150" x2="1068" y2="248"/><line x1="1068" y1="248" x2="998" y2="382"/><line x1="1068" y1="248" x2="1132" y2="340"/><line x1="998" y1="382" x2="1086" y2="486"/><line x1="1132" y1="340" x2="1086" y2="486"/>
<circle cx="960" cy="150" r="7"/><circle cx="1068" cy="248" r="10" fill="#ffffff" stroke="#ffffff"/><circle cx="998" cy="382" r="6"/><circle cx="1132" cy="340" r="5"/><circle cx="1086" cy="486" r="6"/>
</g>
<text x="92" y="150" fill="#8f8f8f" font-size="22" font-weight="500" letter-spacing="4">OPEN SOURCE · SELF-HOSTED</text>
<text x="84" y="330" fill="#ffffff" font-size="200" font-weight="600" letter-spacing="-8">fein</text>
<text x="92" y="410" fill="#c9c9c9" font-size="38" font-weight="400">The memory layer for venture capital.</text>
<text x="92" y="458" fill="#7d7d7d" font-size="25" font-weight="400">Warm intros · meeting prep · deal memory, inside Claude &amp; ChatGPT</text>
<text x="92" y="560" fill="#ededed" font-size="26" font-weight="500">fein.vc</text>
</g>
</svg>
`);

// artifact is body + the end-of-body sprite half, so measure what was written
console.log("built. index.html KB:", Math.round(indexHtml.length / 1024), "| artifact KB:", Math.round((body.length + spriteRest.length) / 1024));
console.log("site files:", fs.readdirSync(out).join(", "));
