const fs = require("fs");
const path = require("path");

const SITE = "https://fein.vc";
const TITLE = "fein · the shared memory of a venture capital team";
// DESC: search-snippet length (~160 chars). DESC_LONG: link previews + JSON-LD.
// Both are written in Simplified Technical English, one idea to a sentence, and
// both hold the approved terms: "your team" for the customer, "context graph"
// for the structure, "source document" for provenance. Never swap in a synonym
// here, because these two strings are what an answer engine quotes back.
const DESC = "fein reads your team's email, calendar, notes, and CRM. It builds one context graph of every relationship your team has. It answers in Claude, ChatGPT, and Cursor.";
const DESC_LONG = "fein reads your team's email, calendar, notes, and CRM. It builds one context graph of every relationship your team has. It answers in Claude, ChatGPT, and Cursor. Each answer carries its source document. Self-hosted, open source, live in 14 days.";
const LASTMOD = "2026-08-12";

// ---- fonts ----
// The *.subset.woff2 files are generated by subset-fonts.py: the full faces are
// a 100-900 weight axis over the whole Latin set, and this site renders 128
// codepoints at the three weight ranges the @font-face descriptors already
// clamp to. Subsetting is therefore lossless and takes 101 KB of font down to
// 42 KB, which is a third of the wire weight of the page.
//
// The risk that buys is tofu: add a character the subset lacks and the browser
// falls back mid-word. assertCharsetCovers below closes that off by failing the
// BUILD instead, so the failure lands here and not on a visitor's screen.
const CHARSET = fs.readFileSync("fonts.charset.txt", "utf8").replace(/\n$/, "");
const sansB64 = fs.readFileSync("GeistSans.subset.woff2").toString("base64");
const monoB64 = fs.readFileSync("GeistMono.subset.woff2").toString("base64");
// Inter (variable 400-600, latin cut) carries body copy, sub headings, buttons
// and nav; Geist is the display face for h1 and h2 only.
const interB64 = fs.readFileSync("Inter.subset.woff2").toString("base64");
// Newsreader italic used to set the section labels here, cut against its own
// charset. The labels are small grey Inter now, so the face, its subset guard
// and its 6 KB of base64 are gone; Newsreader.subset.woff2 and
// fonts.serif.charset.txt are left on disk in case that voice comes back.

// Everything the page can actually render: element text, attributes that surface
// as text (alt/aria-label/title/placeholder/content), CSS content: strings, and
// string literals in the inline scripts. Deliberately over-inclusive -- a false
// alarm costs one character in fonts.charset.txt, a miss costs tofu in production.
function assertCharsetCovers(html, label) {
  const covered = new Set(Array.from(CHARSET));
  ["\n", "\r", "\t"].forEach(c => covered.add(c));
  const decoded = html
    .replace(/&middot;/g, "·").replace(/&minus;/g, "−")
    .replace(/&rarr;/g, "→").replace(/&larr;/g, "←")
    .replace(/&darr;/g, "↓").replace(/&uarr;/g, "↑")
    .replace(/&mdash;/g, "—").replace(/&ndash;/g, "–")
    .replace(/&hellip;/g, "…").replace(/&copy;/g, "©")
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(+d))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)));
  const missing = new Map();
  for (const ch of decoded) if (!covered.has(ch)) missing.set(ch, (missing.get(ch) || 0) + 1);
  if (missing.size) {
    const list = [...missing].map(([c, n]) => `U+${c.codePointAt(0).toString(16).toUpperCase().padStart(4, "0")} ${JSON.stringify(c)} x${n}`);
    throw new Error(
      `${label}: ${missing.size} codepoint(s) outside the font subset -- these would render as tofu:\n  ` +
      list.join("\n  ") + `\nAdd them to src/fonts.charset.txt and re-run subset-fonts.py.`);
  }
}

// ---- inject fonts into shared body ----
let body = fs.readFileSync("fein.tpl.html", "utf8")
  .replace("__GEIST_SANS_B64__", sansB64)
  .replace("__GEIST_MONO_B64__", monoB64)
  .replace("__INTER_B64__", interB64);
if (body.indexOf("__GEIST") > -1 || body.indexOf("__INTER") > -1 || body.indexOf("__NEWSREADER") > -1) throw new Error("font placeholder left");

// ---- brand-logo sprite (symbols referenced by <use href="#l-name">) ----
const LOGOS = { gmail: "logos/gmail.svg", gcal: "logos/gcal.svg", gdrive: "logos/gdrive.svg", attio: "logos/attio.svg", affinity: "logos/affinity.svg", linkedin: "logos/linkedin.svg", notion: "logos/notion.svg", slack: "logos/slack.svg", granola: "logos/granola.svg", claude: "logos/claude.svg", openai: "logos/openai.svg", cursor: "logos/si-cursor.svg", gemini: "logos/si-gemini.svg", perplexity: "logos/si-perplexity.svg", copilot: "logos/si-githubcopilot.svg", github: "logos/github.svg", salesforce: "logos/si-salesforce.svg", dropbox: "logos/si-dropbox.svg", box: "logos/si-box.svg", crunchbase: "logos/si-crunchbase.svg", googlesheets: "logos/si-googlesheets.svg", whatsapp: "logos/whatsapp.svg" };
const MONO = { openai: 1, cursor: 1, gemini: 1, perplexity: 1, copilot: 1, github: 1 }; // monochrome marks -> recolor via currentColor
function symbolFor(name, file) {
  let s = fs.readFileSync(file, "utf8").replace(/<\?xml[^>]*\?>/i, "").trim();
  const vb = (s.match(/viewBox="([^"]+)"/i) || [null, "0 0 24 24"])[1];
  // namespace internal ids so gradients/clips can't collide across logos
  Array.from(s.matchAll(/id="([^"]+)"/g)).map(m => m[1]).forEach(function (id) {
    const p = name + "_" + id;
    s = s.split('id="' + id + '"').join('id="' + p + '"')
         .split('url(#' + id + ')').join('url(#' + p + ')')
         .split('href="#' + id + '"').join('href="#' + p + '"')
         .split('xlink:href="#' + id + '"').join('xlink:href="#' + p + '"');
  });
  let inner = s.replace(/^[\s\S]*?<svg[^>]*>/i, "").replace(/<\/svg>\s*$/i, "");
  if (MONO[name]) inner = '<g fill="currentColor">' + inner.replace(/fill="[^"]*"/gi, "") + '</g>';
  return '<symbol id="l-' + name + '" viewBox="' + vb + '">' + inner + '</symbol>';
}
function spriteOf(names) {
  let s = '<svg width="0" height="0" style="position:absolute;width:0;height:0;overflow:hidden" aria-hidden="true">';
  names.forEach(function (k) { s += symbolFor(k, LOGOS[k]); });
  return s + '</svg>';
}
// The sprite used to sit whole between <body> and the hero, which put ~22 KB of
// below-the-fold SVG in front of the <h1> in the byte stream. On a throttled
// connection first paint then landed with .wrap half-built and the hero grew
// under it: a measured CLS of 0.0635 on 2-in-8 to 7-in-8 loads, depending
// entirely on where the chunk boundary fell. Splitting it takes that to 0/44
// and pulls first paint ~40-56 ms earlier, for no change in bytes sent.
//
// Only the GitHub mark is above the fold (the hero's "Use it for free" button),
// so it stays; the other fifteen are first referenced in #change and below, and
// ride at the end of <body> where they cost the hero nothing.
// The hero carries the picture now: five source documents, the three assistants
// the answer can be asked in, and the citation on every claim. All of those
// marks paint above the fold, so they ship in the head sprite rather than the
// end-of-body one. The guard below is what tells you when this list is stale.
const SPRITE_EARLY = ["github", "gmail", "granola", "linkedin", "gcal", "affinity", "slack", "claude", "openai", "cursor", "whatsapp"];
const spriteHero = spriteOf(SPRITE_EARLY);
const spriteRest = spriteOf(Object.keys(LOGOS).filter(k => SPRITE_EARLY.indexOf(k) < 0));

// Guard the split: a mark used in the hero but defined at the end of the body
// renders as an empty box until the document finishes streaming, which is worse
// than the layout shift this change removes. Fail the build instead.
const heroMarkup = (body.match(/<section id="home"[\s\S]*?<\/section>/) || [""])[0];
const heroRefs = [...new Set(Array.from(heroMarkup.matchAll(/href="#l-([a-z]+)"/g), m => m[1]))];
const late = heroRefs.filter(r => SPRITE_EARLY.indexOf(r) < 0);
if (late.length) throw new Error(
  "logo(s) used in the hero but only defined in the end-of-body sprite: " + late.join(", ") +
  "\nAdd them to SPRITE_EARLY in build.js, or the hero will paint an empty icon while the page streams.");

body = body.replace("__LOGO_SPRITE__", spriteHero);
if (body.indexOf("__LOGO_SPRITE__") > -1) throw new Error("logo sprite placeholder left");

// artifact version = body only (claude.ai wraps head/body), so it carries both halves
fs.writeFileSync("fein-landing.html", body + spriteRest);

// ---- split <style> out to head for the standalone doc ----
const sEnd = body.indexOf("</style>") + "</style>".length;
const styleBlock = body.slice(0, sEnd);
const rest = body.slice(sEnd);

// ---- FAQ: no longer a section on the page. It stays here for llms.txt only,
// which is why there is no FAQPage in the JSON-LD: that markup requires the
// answers to be visible on the page it is served from. ----
const faqs = [
  ["What exactly is fein?", "fein is an open-source data layer for your firm's relationships. It reads your email, calendar, notes, and CRM. It resolves them into one graph. It answers over MCP in Claude, ChatGPT, and Cursor. It is not a CRM that you fill in. It maintains itself."],
  ["How is this different from Affinity or Attio?", "A CRM is a database that your team fills in by hand. fein reads your CRM and everything around it. It resolves this into one graph. The graph stays current automatically. fein answers where your team already works. It sits on top of the CRM. It needs no new data entry."],
  ["What does it cost?", "It costs $5,000 once to build it into your stack. Then you pay a monthly fee priced on fund size: $1,000 each month under $250M, $2,500 from $250M to $1B, $4,000 from $1B to $5B, and a price agreed on a call above $5B. An annual plan, paid in advance, costs 15% less. There is no per-seat pricing. Running it yourself is free forever."],
  ["Can't we build this ourselves?", "Yes. It is open source, so you can clone it. The monthly fee pays for the engineer who keeps it current. Then your engineer can build on top of it."],
  ["What happens if we cancel?", "Nothing stops. It runs on your servers. The graph, the connectors, and every answer stay yours."],
  ["How long does setup take?", "Fourteen days. The date is a commitment. Your part is two short calls. We do everything between them."],
  ["Is our data safe?", "Your data never leaves your infrastructure. fein checks access for each person. Every line of code is open to audit."],
  ["What does it connect to?", "It connects to Gmail, Google Calendar, Drive, LinkedIn, Attio, Affinity, and Granola. Answers appear in Claude, ChatGPT, Gemini, and Cursor. We add new connectors often."]
];

// feature list mirrors the visible #features + #how copy; AI answer engines read this verbatim
const FEATURES = [
  "Warm introduction paths: the weighted shortest path to a founder, an LP, or an operator, and the best person to make the introduction",
  "Meeting briefs: the attendees, how you know each of them, and what was open, from your calendar and inbox, before the meeting starts",
  "Deal memory: every company you saw, the memo, and the exact reason you passed, with each line traced to its source document",
  "Cadence alerts: relationships that drift from their learned rhythm, flagged before they go cold",
  "Entity resolution: every duplicate contact across your tools resolved to one identity, scored from real signals, not an LLM guess",
  "One MCP endpoint: the same cited answer in Claude, ChatGPT, Gemini, and Cursor, from structured graph traversal, not document scraping"
];

// ---- the film (#memory) ----
// 622 frames at 24 fps is 25.916s; PT26S matches the h2 on the page, so the
// markup and the visible copy tell a crawler the same thing. contentUrl points
// at the H.264 cut rather than the AV1 webm because it is the one every crawler
// and every browser can actually decode.
//
// The transcript matters more than the rest of this object put together: the
// film's entire positioning argument is 55 words that exist only as pixels and
// as an audio track, which is to say it is invisible to every search engine and
// every AI assistant that has ever looked at this page. It is transcribed from
// the narration (see video/fein-demo.en.vtt, which carries the same words with
// timings). Since the on-page transcript was removed, this property and that
// .vtt are the only places the narration exists as text.
const VIDEO_NAME = "fein in twenty-six seconds";
const VIDEO_DESC = "A short walkthrough of fein: a partner asks who the warmest path into a company is and what the firm said when it passed, and fein answers with citations from seven documents across four sources, then shows the memory behind the answer and the eight systems it reads.";
const VIDEO_TRANSCRIPT = "Introducing fein. Privacy-first, open-source, agentic memory layer, purpose-built for venture capital. Humans and agents can speak with fein to query and understand facts over time. Team members draw from the same system of record: a single endpoint for all of your AI agents to query and understand your VC's knowledge base.";
const VIDEO_UPLOADED = "2026-08-11";

const ld = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "VideoObject", "@id": SITE + "/#demo-film",
      name: VIDEO_NAME, description: VIDEO_DESC,
      contentUrl: SITE + "/video/fein-demo-1440.mp4",
      thumbnailUrl: [SITE + "/video/fein-demo-poster.jpg"],
      uploadDate: VIDEO_UPLOADED, duration: "PT26S",
      width: 2560, height: 1440, encodingFormat: "video/mp4",
      inLanguage: "en", isFamilyFriendly: true,
      transcript: VIDEO_TRANSCRIPT,
      // the timed captions exist as a real file for machines that want them.
      // Deliberately not wired up as a <track>: Safari and Chromium force-enable
      // caption tracks for readers who have captions on at the OS level, and this
      // film already carries its captions burned into the picture.
      caption: {
        "@type": "MediaObject", contentUrl: SITE + "/video/fein-demo.en.vtt",
        encodingFormat: "text/vtt", inLanguage: "en"
      },
      embedUrl: SITE + "/#memory",
      publisher: { "@id": SITE + "/#org" },
      isPartOf: { "@id": SITE + "/#webpage" },
      about: { "@id": SITE + "/#app" }
    },
    { "@type": "Organization", "@id": SITE + "/#org", name: "fein", alternateName: "Fein", url: SITE + "/", description: DESC_LONG, slogan: "the shared memory of a venture capital team", email: "sales@fein.vc", logo: SITE + "/icon-512.png", image: SITE + "/og.png", sameAs: ["https://github.com/clippycommits/fein"], contactPoint: { "@type": "ContactPoint", contactType: "sales", email: "sales@fein.vc", url: SITE + "/demo" } },
    { "@type": "WebSite", "@id": SITE + "/#website", url: SITE + "/", name: "fein", description: DESC, inLanguage: "en", publisher: { "@id": SITE + "/#org" } },
    { "@type": "WebPage", "@id": SITE + "/#webpage", url: SITE + "/", name: TITLE, description: DESC, isPartOf: { "@id": SITE + "/#website" }, about: { "@id": SITE + "/#app" }, mainEntity: { "@id": SITE + "/#app" }, primaryImageOfPage: { "@type": "ImageObject", contentUrl: SITE + "/og.png", width: 1200, height: 630 }, video: { "@id": SITE + "/#demo-film" }, datePublished: "2026-08-07", dateModified: LASTMOD, inLanguage: "en" },
    {
      "@type": "SoftwareApplication", "@id": SITE + "/#app", name: "fein", alternateName: "Fein",
      applicationCategory: "BusinessApplication", applicationSubCategory: "Relationship intelligence",
      operatingSystem: "Self-hosted (Docker)", description: DESC_LONG, url: SITE + "/",
      provider: { "@id": SITE + "/#org" }, isAccessibleForFree: true, featureList: FEATURES,
      audience: { "@type": "Audience", audienceType: "Venture capital teams" }
    }
  ]
};
const ldScript = '<script type="application/ld+json">' + JSON.stringify(ld) + "</script>";

const headMeta = `<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${TITLE}</title>
<meta name="description" content="${DESC}">
<link rel="canonical" href="${SITE}/">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
<meta name="color-scheme" content="dark">
<meta name="theme-color" content="#08090A">
<meta name="author" content="fein">
<meta name="application-name" content="fein">
<meta name="apple-mobile-web-app-title" content="fein">
<meta name="format-detection" content="telephone=no">
<link rel="icon" href="/favicon.ico" sizes="48x48 32x32 16x16">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="sitemap" type="application/xml" href="/sitemap.xml">
<link rel="alternate" type="text/plain" href="/llms.txt" title="fein for AI assistants (summary)">
<link rel="alternate" type="text/plain" href="/llms-full.txt" title="fein for AI assistants (full page)">
<link rel="preconnect" href="https://gc.zgo.at">
<link rel="preconnect" href="https://fein.goatcounter.com">
<link rel="dns-prefetch" href="https://widget.intercom.io">
<link rel="dns-prefetch" href="https://js.intercomcdn.com">
<link rel="dns-prefetch" href="https://api-iam.intercom.io">
<meta property="og:type" content="website">
<meta property="og:site_name" content="fein">
<meta property="og:locale" content="en_US">
<meta property="og:title" content="${TITLE}">
<meta property="og:description" content="${DESC_LONG}">
<meta property="og:url" content="${SITE}/">
<meta property="og:image" content="${SITE}/og.png">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="fein · the shared memory of a venture capital team">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${TITLE}">
<meta name="twitter:description" content="${DESC}">
<meta name="twitter:image" content="${SITE}/og.png">
<meta name="twitter:image:alt" content="fein · the shared memory of a venture capital team">`;

// GoatCounter (fein.goatcounter.com) — standalone site only, never the artifact
// copy: claude.ai's CSP blocks external scripts. Hash routes count as pages so
// the #get-started funnel is visible.
const analytics = `<script data-goatcounter="https://fein.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
<script>addEventListener("hashchange",function(){if(window.goatcounter&&goatcounter.count)goatcounter.count({path:location.pathname+location.hash})});</script>
<script>window.va=window.va||function(){(window.vaq=window.vaq||[]).push(arguments)}</script>
<script defer src="/_vercel/insights/script.js"></script>
<script defer src="/_vercel/speed-insights/script.js"></script>`;
// The /_vercel/* pair is Vercel Web Analytics + Speed Insights, first-party
// routes that only resolve on the Vercel deployment (both toggled on for
// fein-site); anywhere else they 404 quietly. Also in 404.html by hand.

// PostHog product analytics — standalone site only, never the artifact (same CSP
// reason as GoatCounter). INERT by default: paste a project API key (phc_...) into
// POSTHOG_KEY to enable, an empty string emits nothing and index.html is unchanged.
// Complements GoatCounter + Vercel with funnels and session insight on the
// #get-started flow. NOTE: confirm the tool with Daniel ("postdoc" was dictated)
// and pick the region host before enabling. Official array.js loader.
const POSTHOG_KEY = ""; // e.g. "phc_..." — leave empty to keep PostHog disabled
const POSTHOG_HOST = "https://us.i.posthog.com"; // EU: https://eu.i.posthog.com
const posthog = POSTHOG_KEY ? `
<script>!function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.crossOrigin="anonymous",p.async=!0,p.src=s.api_host.replace(".i.posthog.com","-assets.i.posthog.com")+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="init capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug getPageViewId captureTraceFeedback captureTraceMetric".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);posthog.init("${POSTHOG_KEY}",{api_host:"${POSTHOG_HOST}",person_profiles:"identified_only",capture_pageview:true})</script>` : "";

// Intercom messenger — standalone site only, never the artifact (same CSP
// reason as GoatCounter). Anonymous visitor mode: no user fields on a
// marketing page. The snippet is what @intercom/messenger-js-sdk does
// internally; the site has no bundler so the npm package doesn't apply.
const INTERCOM_APP_ID = "i91a73cr";
const INTERCOM_API_BASE = "https://api-iam.intercom.io"; // EU: api-iam.eu.intercom.io / AU: api-iam.au.intercom.io
// A custom launcher (the Intercom bubble mark + an online dot + "Last seen 3m
// ago") replaces Intercom's default bubble: hide_default_launcher + a
// custom_launcher_selector pointed at #fein-chat. The whole block is wrapped in
// <!--fein-chat--> markers so rederive-tpl.js can strip it back out cleanly.
const intercom = INTERCOM_APP_ID ? `
<!--fein-chat:start-->
<style>
#fein-chat{position:fixed;right:20px;bottom:20px;z-index:2147483000;display:inline-flex;align-items:center;gap:10px;margin:0;padding:9px 15px 9px 9px;font-family:var(--font);color:var(--fg);background:var(--bg-2);border:1px solid var(--line);border-radius:999px;cursor:pointer;box-shadow:0 1px 0 rgba(255,255,255,.04) inset,0 2px 8px rgba(0,0,0,.5),0 16px 40px -12px rgba(0,0,0,.85);opacity:0;transform:translateY(6px);transition:opacity .3s ease,transform .3s cubic-bezier(.22,.61,.36,1),border-color .2s ease,box-shadow .2s ease;-webkit-tap-highlight-color:transparent}
#fein-chat.fc-in{opacity:1;transform:none}
#fein-chat:hover{border-color:var(--line-2);transform:translateY(-1px);box-shadow:0 1px 0 rgba(255,255,255,.05) inset,0 2px 8px rgba(0,0,0,.5),0 22px 52px -12px rgba(0,0,0,.9)}
#fein-chat:focus-visible{outline:2px solid var(--blue);outline-offset:3px}
/* the bubble is a solid glyph with the smile knocked out of it, so the smile is
   stroked in the disc colour: --fc-disc has to stay opaque and stay in sync
   with the background here, not the translucent white the fein mark sat on. */
#fein-chat .fc-mark{--fc-disc:var(--blue);position:relative;flex:none;display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:var(--fc-disc);color:#fff}
#fein-chat .fc-mark svg{display:block}
#fein-chat .fc-dot{position:absolute;right:0;bottom:1px;width:10px;height:10px;border-radius:50%;background:#30d158;box-shadow:0 0 0 2px var(--bg-2)}
#fein-chat .fc-txt{display:flex;flex-direction:column;align-items:flex-start;gap:1px;line-height:1.2;text-align:left}
#fein-chat .fc-txt b{font-weight:600;font-size:13px;letter-spacing:-.01em;color:var(--fg)}
#fein-chat .fc-txt span{font-size:11.5px;font-weight:450;color:var(--muted)}
#fein-chat.fc-open{opacity:0;transform:translateY(6px);pointer-events:none}
@media(max-width:520px){#fein-chat{padding:9px;gap:0}#fein-chat .fc-txt{display:none}}
@media(prefers-reduced-motion:reduce){#fein-chat,#fein-chat.fc-in{transition:opacity .2s ease;transform:none}}
</style>
<button type="button" id="fein-chat" aria-label="Chat with the fein team. Last seen 3 minutes ago.">
<span class="fc-mark"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" aria-hidden="true"><path d="M7 4h10a3 3 0 0 1 3 3v13l-3.5-3.4H7a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3z" fill="currentColor"/><path d="M8.8 10.6c.9 1.5 2.05 2.25 3.2 2.25s2.3-.75 3.2-2.25" stroke="var(--fc-disc)" stroke-width="1.7" stroke-linecap="round"/></svg><span class="fc-dot"></span></span>
<span class="fc-txt"><b>Chat with us</b><span>Last seen 3m ago</span></span>
</button>
<script>window.intercomSettings={api_base:"${INTERCOM_API_BASE}",app_id:"${INTERCOM_APP_ID}",hide_default_launcher:true,custom_launcher_selector:"#fein-chat"}</script>
<!-- Intercom, booted on first interaction instead of on window.load.

     Measured on the live page with a real Chrome UA (a headless UA makes the
     widget bail, which is why this hid from the earlier baseline): 10 requests,
     908 KB and up to 570 ms of post-load main-thread work, spent on every
     visitor including the ones who bounce off the hero.

     Gating it on the launcher alone would be the bigger saving, but it would
     also stop Intercom seeing anonymous visitors at all: no visitor records and
     no proactive outbound messages, which do fire today despite
     hide_default_launcher. That is a sales decision, not a performance one. So
     the trigger is the first sign of a real human instead: any scroll, pointer
     move, key or touch. A bouncer costs nothing, an engaged visitor is on
     Intercom within a second of moving, and either way it is off the load path.

     The queueing stub is installed synchronously, so the onShow/onHide handlers
     below and a click-time Intercom("show") queue and replay on boot. -->
<script>(function(){var w=window,d=document;var ic=w.Intercom;if(typeof ic==="function"){ic("reattach_activator");ic("update",w.intercomSettings);return}
var i=function(){i.c(arguments)};i.q=[];i.c=function(a){i.q.push(a)};w.Intercom=i;
var started=false,EV=["pointermove","pointerdown","touchstart","keydown","scroll","wheel"];
function boot(){if(started)return;started=true;EV.forEach(function(e){w.removeEventListener(e,boot,{passive:true,capture:true})});
var s=d.createElement("script");s.async=true;s.src="https://widget.intercom.io/widget/${INTERCOM_APP_ID}";d.head.appendChild(s)}
EV.forEach(function(e){w.addEventListener(e,boot,{passive:true,capture:true,once:true})});
var b=d.getElementById("fein-chat");
if(b)b.addEventListener("click",function(){boot();w.Intercom("show")});
if(location.hash==="#chat")boot()})()</script>
<script>(function(){var b=document.getElementById("fein-chat");if(!b)return;requestAnimationFrame(function(){requestAnimationFrame(function(){b.classList.add("fc-in")})});if(window.Intercom){Intercom("onShow",function(){b.classList.add("fc-open")});Intercom("onHide",function(){b.classList.remove("fc-open")})}})()</script>
<!--fein-chat:end-->` : "";

const indexHtml = `<!doctype html>
<html lang="en">
<head>
${headMeta}
${styleBlock}
${ldScript}
</head>
<body>
${rest}
${spriteRest}
${analytics}${posthog}${intercom}
</body>
</html>`;

// ---- write site ----
const out = "..";
fs.mkdirSync(out, { recursive: true });
assertCharsetCovers(indexHtml, "index.html");
fs.writeFileSync(path.join(out, "index.html"), indexHtml);

// robots.txt — welcome AI answer engines explicitly
const aiBots = ["GPTBot", "OAI-SearchBot", "ChatGPT-User", "ClaudeBot", "Claude-User", "Claude-SearchBot", "Claude-Web", "anthropic-ai", "PerplexityBot", "Perplexity-User", "Google-Extended", "Google-CloudVertexBot", "Google-NotebookLM", "GoogleAgent-Mariner", "Applebot-Extended", "Bytespider", "CCBot", "Amazonbot", "Meta-ExternalAgent", "Meta-ExternalFetcher", "cohere-ai", "cohere-training-data-crawler", "AI2Bot", "DuckAssistBot", "YouBot", "MistralAI-User", "DeepSeekBot", "Diffbot", "Timpibot", "omgilibot", "Webzio-Extended", "kagi-fetcher"];
const robots = `# fein · the graph for venture capital teams
# AI assistants welcome. Summary: ${SITE}/llms.txt · Full page: ${SITE}/llms-full.txt

User-agent: *
Allow: /

${aiBots.map(b => `User-agent: ${b}\nAllow: /`).join("\n\n")}

Sitemap: ${SITE}/sitemap.xml
`;
fs.writeFileSync(path.join(out, "robots.txt"), robots);

// sitemap.xml
fs.writeFileSync(path.join(out, "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
  <url><loc>${SITE}/</loc><lastmod>${LASTMOD}</lastmod><changefreq>weekly</changefreq><priority>1.0</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image><video:video><video:thumbnail_loc>${SITE}/video/fein-demo-poster.jpg</video:thumbnail_loc><video:title>${VIDEO_NAME}</video:title><video:description>${VIDEO_DESC}</video:description><video:content_loc>${SITE}/video/fein-demo-1440.mp4</video:content_loc><video:duration>26</video:duration><video:publication_date>${VIDEO_UPLOADED}</video:publication_date><video:family_friendly>yes</video:family_friendly><video:live>no</video:live></video:video></url>
  <url><loc>${SITE}/pe</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority><image:image><image:loc>${SITE}/og.png</image:loc></image:image></url>
  <url><loc>${SITE}/demo</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>0.9</priority></url>
  <url><loc>${SITE}/privacy</loc><lastmod>${LASTMOD}</lastmod><changefreq>yearly</changefreq><priority>0.3</priority></url>
  <url><loc>${SITE}/terms</loc><lastmod>${LASTMOD}</lastmod><changefreq>yearly</changefreq><priority>0.3</priority></url>
</urlset>
`);

// ---- legal pages (privacy, terms): standalone docs served at /privacy and
// /terms via directory-index files. Same font inlining as the main template. ----
["privacy", "terms"].forEach(function (slug) {
  let page = fs.readFileSync(path.join("legal", slug + ".html"), "utf8")
    .split("__GEIST_SANS_B64__").join(sansB64)
    .split("__INTER_B64__").join(interB64)
    .split("__LASTMOD__").join(LASTMOD);
  if (page.indexOf("__GEIST") > -1 || page.indexOf("__INTER") > -1 || page.indexOf("__LASTMOD__") > -1) throw new Error("legal placeholder left in " + slug);
  fs.mkdirSync(path.join(out, slug), { recursive: true });
  assertCharsetCovers(page, slug + "/index.html");
  fs.writeFileSync(path.join(out, slug, "index.html"), page);
});

// ---- segment landing pages: standalone marketing docs served at /<slug> via a
// directory-index file, the same shape as the legal pages. These are the pages
// cold outbound points at, so unlike /privacy and /terms they carry the
// analytics block: the whole point is knowing which sends convert. Their form
// posts to the same /api/enquiry endpoint the modal on the index page uses. ----
["pe", "demo"].forEach(function (slug) {
  let page = fs.readFileSync(path.join("pages", slug + ".html"), "utf8")
    .split("__GEIST_SANS_B64__").join(sansB64)
    .split("__INTER_B64__").join(interB64)
    .split("__LASTMOD__").join(LASTMOD)
    .split("__ANALYTICS__").join(analytics);
  if (page.indexOf("__GEIST") > -1 || page.indexOf("__INTER") > -1 || page.indexOf("__ANALYTICS__") > -1) throw new Error("page placeholder left in " + slug);
  fs.mkdirSync(path.join(out, slug), { recursive: true });
  assertCharsetCovers(page, slug + "/index.html");
  fs.writeFileSync(path.join(out, slug, "index.html"), page);
});

// llms.txt — structured summary for AI crawlers (llms-full.txt carries the whole page)
const LLMS_SUMMARY = `> fein is the open-source context graph for an investment team. It is the shared memory that the whole team can query. It serves venture capital teams and private equity teams. It reads the team's email, calendar, notes, and CRM. It builds one context graph of every relationship the team has. The context graph shows who knows whom, and how strongly. fein scores this from real signals, not a guess. It serves the context graph to AI tools like Claude, ChatGPT, and Cursor over one MCP endpoint. Each answer arrives with its source document attached: warm introductions, meeting preparation, deal history, and the reason the team passed. AI tools traverse a deterministic map. They do not scrape documents and guess. fein is live in 14 days. It is self-hosted on the team's own infrastructure. It is open source. Pricing: $5,000 to build once, then a monthly fee priced on fund size, from $1,000 each month. There is no per-seat pricing. It is free if the team runs it.`;
fs.writeFileSync(path.join(out, "llms.txt"), `# fein

${LLMS_SUMMARY}

Updated: ${LASTMOD}. Full page content in Markdown: ${SITE}/llms-full.txt

## What fein does
- Find the warmest introduction to a founder, an LP, or an operator. See who should make it.
- Prepare for meetings. See who is in the room, how you know them, and what you last discussed.
- Recall every company the team saw, and the exact reason it passed.
- Flag relationships that go cold, by each contact's own cadence.

## How it works
- fein reads your existing systems: email, calendar, Google Drive, LinkedIn, and CRMs like Attio and Affinity. It builds the context graph automatically. You keep no CRM up to date by hand.
- It serves answers over one MCP endpoint. You query it from Claude, ChatGPT, Gemini, Cursor, or any MCP client.
- We deploy it into your stack. It is live in 14 days. Your team joins two short calls.

## Your CRM stays
- fein works with 30+ tools. It reads the CRM and everything around it, then resolves the whole picture into one graph.
- It replaces no system, migrates no data, and asks the team for no new data entry. If the CRM is out of date, fein is still current, because it reads the record the team makes anyway.
- CRM and deal systems: DealCloud, Affinity, Salesforce, Attio, HubSpot, Airtable.
- Email and calendar: Gmail, Google Calendar, Outlook, Microsoft 365.
- Files and data rooms: Google Drive, SharePoint, OneDrive, Dropbox, Box, DocSend.
- Meetings, notes and chat: Granola, Zoom, Google Meet, Slack, Microsoft Teams, Notion.
- People and market data: LinkedIn, PitchBook, Crunchbase, Harmonic.
- Portfolio and back office: Carta, Standard Metrics, Google Sheets, Excel.

## For private equity
- fein serves private equity firms as well as venture capital firms. The page for private equity is ${SITE}/pe.
- An intermediary is a banker, a broker, an accountant, or a lawyer who brings a firm deals. A private equity firm has thousands of them. Their record sits in the firm's email.
- fein lists every intermediary who sends the firm deals. It scores each relationship from real signal. It names the person at the firm who owns each relationship. It flags the relationships that go quiet.
- It shows which intermediary sent each deal, what the team said, and the exact reason the firm passed, with the source document for each line.
- It works with DealCloud, Affinity, Salesforce, and Attio. It replaces no system and migrates no data.

## Pricing
- $5,000 to build once. That fee builds fein into the firm's stack.
- Then a monthly fee, priced on fund size, never per seat: under $250M is $1,000 each month; $250M to $1B is $2,500; $1B to $5B is $4,000; over $5B is priced on a call.
- The monthly fee keeps the connectors working, keeps the graph current, and builds new answers on request.
- An annual plan, paid in advance, costs 15% less.
- It is month to month, with no lock-in. If you cancel, the self-hosted software and the graph stay yours.
- Running it yourself is free forever. The code is MIT licensed.

## Security and data
- It is self-hosted in the team's own environment. Data never leaves it. There is no telemetry and no control plane.
- It is open source and auditable from end to end. A team can clone the repo and run fein. The paid offer is setup and upkeep.
- One token gates the dashboard, the API, and the agent endpoint.
- Access is per person. Each person's sensitive sources live in a private layer, and fein enforces the scoping inside every query.
- Every ingest, merge, and review decision is written to an append only audit trail, with the person or agent that made it.

## Contact
- [Get a demo](${SITE}/demo): talk to sales about a 14 day build
- [Email sales](mailto:sales@fein.vc): sales@fein.vc

## Links
- [fein for private equity](${SITE}/pe): the page for private equity firms, with pricing by fund size
- [Source on GitHub](https://github.com/clippycommits/fein): MIT licensed, free to self-host
- [Full page content for LLMs](${SITE}/llms-full.txt): the whole page in Markdown
- [Sitemap](${SITE}/sitemap.xml): every indexable URL
`);

// llms-full.txt — the whole page, mirrored in Markdown for AI answer engines.
// Every line here restates visible site copy; keep it in sync when copy changes.
fs.writeFileSync(path.join(out, "llms-full.txt"), `# fein · the shared memory of a venture capital team

${LLMS_SUMMARY}

Updated: ${LASTMOD}. This file mirrors the full content of ${SITE}/ for AI assistants and answer engines. Summary version: ${SITE}/llms.txt

## What fein is

fein reads your team's email, calendar, notes, and CRM. It builds one context graph of every relationship your team has. It answers in Claude, ChatGPT, and Cursor. Each answer carries its source document. Self-hosted, open source, live in 14 days.

You add no new CRM. Your team logs nothing. The context graph builds itself from the record your team already makes.

It reads and answers in the tools you already use: Gmail, Google Calendar, Drive, Attio, LinkedIn, Granola, Notion, Slack, Claude, ChatGPT, Gemini, Cursor, Perplexity, and Copilot.

## The film: fein in twenty-six seconds

There is a twenty-six second narrated walkthrough on the page, at ${SITE}/#memory (video: ${SITE}/video/fein-demo-1440.mp4). Its narration, verbatim:

"Introducing fein. Privacy-first, open-source, agentic memory layer, purpose-built for venture capital. Humans and agents can speak with fein to query and understand facts over time. Team members draw from the same system of record: a single endpoint for all of your AI agents to query and understand your VC's knowledge base."

What it shows: a partner asks "Who is the warmest path into Halo Compute, and what did we say when we passed?" fein reads seven documents across four sources in 1.8 seconds and answers with six citations. Dev Raman is the warmest path. The firm passed in January 2025 for two stated reasons, and three of the facts behind that decision are no longer true. The film then shows the memory behind the answer, every fact carrying the document it was read out of, and the eight systems fein reads continuously.

## What changes when a fact stops being true

fein holds one live record per company and retires facts that stop being true rather than overwriting them. A retired fact keeps the dates it was true between, so the history stays queryable: you can ask what the firm believed at the moment it made a decision, not only what is true now. Nobody opens a CRM to correct a title, and no stale row survives because the person who knew was on holiday.

## How it works: nobody enters data, the graph builds itself

fein reads the record your team already makes. It resolves that record into one live graph: who exists, who knows whom, and how well. Your AI tools read the graph. They stop guessing.

1. Reads everything your team already uses: your inbox, calendar, Drive, LinkedIn, and CRM, read continuously. Your team logs nothing.
2. Resolves it into one identity per person, not a hundred duplicates: fein resolves every copy of a contact into one identity. It scores the strength from real signals (meetings, replies, and shared documents), not an LLM guess.
3. Answers wherever your team asks: ask in Claude, ChatGPT, Gemini, or Cursor over one MCP endpoint. You get the same answer every time, with the email behind it.

## What you get: four questions your team asks every week

The warm introduction. The brief before the meeting. The reason you passed. The relationship that goes quiet. fein answers each one from your team's history, in seconds.

### Your team already has the introduction you need.
Ask for the warmest path to a founder or an LP. fein reads the real graph of who meets and emails whom. It weighs each hop. It names the best person to make the introduction. This is not only the person who knows them.

### Get a brief before each meeting.
fein shows the attendees, how you know each of them, and what was open. It gets this from your calendar and inbox. It is on your screen before the meeting starts.

### Ask one question to see why you passed.
A company can come back for its next round. Then fein shows the meeting, the memo, and the exact reason in seconds. It traces each line to its source document.

### Relationships go cold. fein sees it first.
fein learns the rhythm of each relationship from your real history. Then it flags the ones that drift away from it. It uses dates and intervals, not a guess.

## Your CRM stays: it sits on top of the systems you run today

fein works with 30+ tools. It reads your CRM and everything around it, then resolves the whole picture into one graph. It replaces no system, migrates no data, and asks your team for no new data entry. If your CRM is out of date, fein is still current, because it reads the record your team makes anyway.

- CRM and deal systems: DealCloud, Affinity, Salesforce, Attio, HubSpot, Airtable
- Email and calendar: Gmail, Google Calendar, Outlook, Microsoft 365
- Files and data rooms: Google Drive, SharePoint, OneDrive, Dropbox, Box, DocSend
- Meetings, notes and chat: Granola, Zoom, Google Meet, Slack, Microsoft Teams, Notion
- People and market data: LinkedIn, PitchBook, Crunchbase, Harmonic
- Portfolio and back office: Carta, Standard Metrics, Google Sheets, Excel
- 30+ tools in all. If your team runs something else, we read that too.

## Security

Your data never leaves your servers. fein reads your inbox, calendar, and CRM to do its work. It does this on your own servers. You can read all of the code.

- Always self-hosted. It runs on your infrastructure. It sends nothing to us.
- Open source, end to end. Every line that touches your data is public. Read it before you run it.
- One token, every surface. The dashboard, the API, and the agent endpoint sit behind the same gate.
- Private by person. Each person's sensitive sources stay in their own layer inside the shared graph.
- Every change is written down. Ingests, merges, and decisions are logged with the person or agent that made them.
- Nothing phones home. No telemetry, no analytics, and no control plane of ours to trust.

## Managed installation: we deploy fein in two weeks

We deploy fein in two weeks. Then it works on its own. Your only part is two short calls. By day fourteen, fein holds your team's full history, and it works like it has been here for years. It drafts the brief before each meeting, and it shows the source for each answer.

- Day 1, we connect your systems: on the first call, we connect your email, calendar, Drive, LinkedIn, and CRM. This runs on your own servers.
- Days 2-13, it reads your full history: it reads years of email, meetings, and documents. It joins every copy of each person into one record. The whole team shares this record. Nobody maintains it by hand.
- Day 14, you check it, then it goes live: on a second short call, you check the answers against what you know. Then fein goes live. It holds your team's full history, like a colleague of many years.

## For private equity: ${SITE}/pe

fein serves private equity firms as well as venture capital firms. The page at ${SITE}/pe describes the same product in the language a deal team uses.

An intermediary is a banker, a broker, an accountant, or a lawyer who brings a firm deals. A private equity firm has thousands of them, and the record of those relationships sits in ten thousand emails. Four problems follow from that. Coverage is a guess, because the CRM shows one picture and the inbox shows another. Relationships go quiet in silence, and the firm learns this when the next deal goes to a competitor. Ownership leaves when a partner leaves, because what the partner knew was never written down. Deal history is not searchable, because the memo, the reason, and the intermediary sit in three systems and one person's memory.

fein answers four questions for a deal team. It lists every intermediary who sends the firm deals, scored from real signal, with the owner of each relationship named. It flags each relationship that drifts away from its own rhythm, with the last contact and the colleague who must make the call. It shows which intermediary sent each deal, what the team said, and the exact reason the firm passed, with the source document for each line. It finds the shortest real path to a management team, a seller, an operator, or an LP, and names the best colleague to make the introduction.

fein works with DealCloud, Affinity, Salesforce, and Attio. It reads the CRM and everything around it. It replaces no system, it migrates no data, and it asks the team for no new data entry.

## Pricing

Every investment team needs a data engineer. Now every team can afford one.

| Option | Price | What you get |
| --- | --- | --- |
| A data hire | $200,000 per year | Skilled, but one person. The graph stays in their head. |
| fein | $5,000 once + a monthly fee priced on fund size | We build it into your stack in two weeks and keep it current for you. Live in 14 days. |
| Clone it yourself | $0 forever | The same code we deploy for clients. You run it and you maintain it. |

The monthly fee is priced on fund size, and never per seat.

| Fund size | Monthly |
| --- | --- |
| Under $250M | $1,000 |
| $250M to $1B | $2,500 |
| $1B to $5B | $4,000 |
| Over $5B | Priced on a call |

The fein plan reads your inbox, calendar, Drive, LinkedIn, and CRM. It resolves entities to one identity per person. It scores every relationship from real signals, not a guess. It answers over one MCP endpoint in Claude, ChatGPT, Gemini, and Cursor. It is open source and runs on your servers. We keep the connectors working through every API change. We build new answers when your team asks.

A firm under $250M pays about $17,000 in the first year. That is less than one month of a data hire. An annual plan, paid in advance, costs 15% less. It is month to month, open source, and self-hosted. If you cancel, everything continues to run.

## FAQ

${faqs.map(([q, a]) => `### ${q}\n${a}`).join("\n\n")}

## Contact

- [Get a demo](${SITE}/demo): the form on the site, two short calls to go live
- [Email sales](mailto:sales@fein.vc): sales@fein.vc
- [Get the repo](https://github.com/clippycommits/fein): the source on GitHub, MIT licensed, free to self-host
`);

// favicon.svg — theme-adaptive graph mark
fs.writeFileSync(path.join(out, "favicon.svg"), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<style>line{stroke:#000;stroke-width:2.4}circle{fill:#000}@media(prefers-color-scheme:dark){line{stroke:#fff}circle{fill:#fff}}</style>
<line x1="7" y1="24" x2="22" y2="9"/><line x1="22" y1="9" x2="24.5" y2="24"/>
<circle cx="7" cy="24" r="3.6"/><circle cx="22" cy="9" r="3.6"/><circle cx="24.5" cy="24" r="2.4"/>
</svg>
`);

// web manifest
fs.writeFileSync(path.join(out, "site.webmanifest"), JSON.stringify({
  name: "fein", short_name: "fein", description: "The shared memory of a venture capital team.",
  start_url: "/", display: "standalone", background_color: "#08090A", theme_color: "#08090A",
  icons: [
    { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
    { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
    { src: "/icon-512-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    { src: "/favicon.svg", sizes: "any", type: "image/svg+xml" }
  ]
}, null, 2));

// GitHub Pages helpers
fs.writeFileSync(path.join(out, "CNAME"), "fein.vc\n");
fs.writeFileSync(path.join(out, ".nojekyll"), "");

// og.svg — square canvas (1200x1200) with the 1200x630 design centered vertically,
// so a centered crop recovers it undistorted (qlmanage renders square SVGs 1:1).
fs.writeFileSync("og.svg", `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1200" viewBox="0 0 1200 1200">
<defs><style>
@font-face{font-family:'Geist';font-weight:400 600;src:url(data:font/woff2;base64,${sansB64}) format('woff2');}
text{font-family:'Geist','Helvetica Neue',Arial,sans-serif}
</style></defs>
<rect width="1200" height="1200" fill="#000000"/>
<g transform="translate(0,285)">
<g stroke="#2b2b2b" stroke-width="2" fill="#2b2b2b">
<line x1="960" y1="150" x2="1068" y2="248"/><line x1="1068" y1="248" x2="998" y2="382"/><line x1="1068" y1="248" x2="1132" y2="340"/><line x1="998" y1="382" x2="1086" y2="486"/><line x1="1132" y1="340" x2="1086" y2="486"/>
<circle cx="960" cy="150" r="7"/><circle cx="1068" cy="248" r="10" fill="#ffffff" stroke="#ffffff"/><circle cx="998" cy="382" r="6"/><circle cx="1132" cy="340" r="5"/><circle cx="1086" cy="486" r="6"/>
</g>
<text x="92" y="150" fill="#8f8f8f" font-size="22" font-weight="500" letter-spacing="4">THE GRAPH FOR VC TEAMS</text>
<text x="84" y="330" fill="#ffffff" font-size="200" font-weight="600" letter-spacing="-8">fein</text>
<text x="92" y="410" fill="#c9c9c9" font-size="38" font-weight="400">The relationship layer your AI acts on.</text>
<text x="92" y="458" fill="#7d7d7d" font-size="25" font-weight="400">Warm intros · meeting prep · deal memory, inside Claude &amp; ChatGPT</text>
<text x="92" y="560" fill="#ededed" font-size="26" font-weight="500">fein.vc</text>
</g>
</svg>
`);

// artifact is body + the end-of-body sprite half, so measure what was written
console.log("built. index.html KB:", Math.round(indexHtml.length / 1024), "| artifact KB:", Math.round((body.length + spriteRest.length) / 1024));
console.log("site files:", fs.readdirSync(out).join(", "));
